### ISSUE TITLE
session.Manager does not properly close if connection was closed with non-nil error

### ISSUE THREAD

**Issue by dgstevens** [mafredri/cdp#111]
#74 propagates the error which closes a connection. This causes the check in session.Manager. watch's isClosing function to fail because the cause is the original error instead of rpcc.ErrConnClosing. This prevents the Manager's goroutine from properly terminating, and it ends up spinning and continuously polling.

**Comment by mafredri** [comment]
Ah, unfortunate byproduct :(. Thanks for reporting, I'll see what can be done about it.

**Comment by mafredri** [comment]
@dgstevens does #112 fix your issue?

**Comment by dgstevens** [comment]
Yeah, it looks like that change should fix it.
