### ISSUE TITLE
BrowserContextID is not accessible anymore

### ISSUE THREAD

**Issue by ziflex** [mafredri/cdp#115]
Hey,

In the latest version of the package, you [moved](https://github.com/mafredri/cdp/commit/64172c483a364d586d94edc08ae264822e29a150#diff-d07c35dbc7267d4328c34578e492bed0R10) ``target.BrowserContextID`` to ``internal`` module that makes use of [incognito mode](https://github.com/mafredri/cdp/blob/master/protocol/target/command.go#L139) impossible.

Is there a new way how to open a browser tab in incognito mode?

**Comment by mafredri** [comment]
You can use `browser.ContextID`. It's unfortunate but we have to do this with circular dependencies. But type aliases makes this quite smooth. I've tried to make it discoverable via GoDocs but perhaps they don't show up in the editor?

https://github.com/mafredri/cdp/blob/158b1d3eb5ec0e6523b25f660b82ec4dc5316d62/protocol/internal/browser.go#L7

**Comment by ziflex** [comment]
It works, thank you!
