### ISSUE TITLE
Is possible to wait for an Ajax request?

### ISSUE THREAD

**Issue by mperezguendulain** [mafredri/cdp#116]
Hi, firstly thanks for this amazing package!

I have the next problem:
I need to generate a PDF file of a page, but this page when you enter only show a header with options, the other parts of the page are loaded when you select some option. For example, when I click over the option two in the header, this option shows a map (with google maps).

Then I would like to know how to wait until this part of the page was completely load in order to generate the pdf after this.

I need to wait until the ajax request to be finished because there are other places where I need to wait too.

Thanks in advance.

**Comment by mafredri** [comment]
Hey, glad you like the project!

To solve your issue I believe #99 should be of interest to you. It outlines a few different options, keeping track of network requests, waiting for the networkidle2 event, etc.

---

Another option could be to write some code to detect e.g. when an element is present/visible. I wrote some code for this a while back but I haven't published it as of yet.

<details>
    <summary>Example Wait code</summary>

```go
func Eval(ctx context.Context, c *cdp.Client, expr string, out interface{}) error {
	args := runtime.NewEvaluateArgs(expr).
		SetReturnByValue(out != nil)
	return eval(ctx, c, args, out)
}

func EvalPromise(ctx context.Context, c *cdp.Client, expr string, out interface{}) error {
	args := runtime.NewEvaluateArgs(expr).
		SetReturnByValue(out != nil).
		SetAwaitPromise(true)
	return eval(ctx, c, args, out)
}

func eval(ctx context.Context, c *cdp.Client, args *runtime.EvaluateArgs, out interface{}) error {
	reply, err := c.Runtime.Evaluate(ctx, args)
	if err != nil {
		return err
	}
	if reply.ExceptionDetails != nil {
		return reply.ExceptionDetails
	}
	if out == nil {
		return nil
	}
	return json.Unmarshal(reply.Result.Value, out)
}

func Wait(ctx context.Context, c *cdp.Client, expr string) error {
	return poll(ctx, func() (bool, error) {
		var ok bool
		if err := Eval(ctx, c, expr, &ok); err != nil {
			return false, err
		}
		return ok, nil
	})
}

func poll(ctx context.Context, fn func() (bool, error)) error {
	t := time.NewTimer(1 * time.Second)
	if !t.Stop() {
		<-t.C
	}

	for {
		ok, err := fn()
		if err != nil {
			return err
		}
		if ok {
			return nil
		}

		t.Reset(10 * time.Millisecond)
		select {
		case <-t.C:
		case <-ctx.Done():
			return ctx.Err()
		}
	}
}
```

</details>

With the above code, you could for example: `Wait(ctx, c, "document.querySelector('div.findme') !== null")`. But keep in mind that this code has not been tested much, and may contain bugs 😄.

**Comment by mperezguendulain** [comment]
Thanks, I will check the issue and your code. Have a good day!
