### ISSUE TITLE
Lifecycle events not fire in order and this ones are fired twice

### ISSUE THREAD

**Issue by mperezguendulain** [mafredri/cdp#117]
Hello @mafredri 

I am working on the creation of a service to generate a PDF file of a web page.
First, I create an application to do generate a pdf file from a URL. I am waiting for networkIdle event to know when the page was completely loaded, as you mention here: https://github.com/mafredri/cdp/issues/99

This is the application I wrote:
https://gist.github.com/mperezguendulain/a07c179759cb855b6464c0ef6d1b3d00

In this application, always the page is loaded completely, and the lifecycle events was fire well (except I don't understand why some events are fire twice):

    init
    firstPaint
    firstContentfulPaint
    firstImagePaint
    firstMeaningfulPaintCandidate
    init
    DOMContentLoaded
    DOMContentLoaded
    networkAlmostIdle
    networkIdle

I made little changes to the code in order to use it on the server. This is the code:
https://gist.github.com/mperezguendulain/11c962b01d008465f207616b022b998b

But in the server sometimes the page is not loaded completely. And this is because the lifecycle events are not fired in order, I remove this chunk of code in order to check this:

    if ev.Name == "networkIdle" {
        break
    }

This is the order of the lifecycle events when this problem occurs:

    networkAlmostIdle
    networkIdle
    init
    firstPaint
    firstContentfulPaint
    firstImagePaint
    firstMeaningfulPaintCandidate
    init
    DOMContentLoaded
    DOMContentLoaded
    networkAlmostIdle
    networkIdle
    networkAlmostIdle
    firstMeaningfulPaint
    networkIdle
    load

As you can see, the lifecycle events are fired twice.

Could you please tell me what I am doing wrong? Or tell me what I should read to understand what's going on?

I will appreciate your help.
Thanks in advance.

**Comment by mperezguendulain** [comment]
Today I did more test in the application without the server, and I test with the netflix page: **https://netflix.com/mx** and I could see that the error happens too

**Comment by mafredri** [comment]
Hi, apologies for the long delay in getting back to you on this.

I've tried to reproduce your issue but I've been unable to. Which version of Chrome are you using?

To debug this further, I'd recommend logging all fields from `LifecycleEventReply` since these events could be coming from some other place, say another tab, perhaps an iframe, etc. You could try to make sure it matches the FrameID / LoaderID you get back from `c.Page.Navigate`.
