### ISSUE TITLE
Non-wrapped error

### ISSUE THREAD

**Issue by GabdaZM** [mafredri/cdp#123]
In protocol/internal/error.go, in `func (e OpError) Error() string` the error is composed with `fmt.Sprintf` instead of wrapping the error.
This way, when I have a `cdp.Runtime: CallFunctionOn: context deadline exceeded` error, the `errors.Is(err, context.DeadlineExceeded)` check returns with false.

Would it be possible to modify it to use `errors.Wrap()` instead?

**Comment by mafredri** [comment]
Hi, I did an early experiment on this in a branch that has not yet been merged (commit https://github.com/mafredri/cdp/commit/3db9e5e5afaf4bde69f42d13401c971cd1ee152f). Unfortunately it fell into oblivion for 1.5 years 😬.

Would the changes done above work for you? I'll look into getting it merged.

**Comment by GabdaZM** [comment]
Thanks for the fast response! Yes, I think so. The new `Unwrap()` function in protocol/internal/error.go looks promising. Though I don't really understand the other changes, but those might be unrelated.

**Comment by mafredri** [comment]
@GabdaZM this was released in v0.30.0.
