### ISSUE TITLE
Rpc command not found

### ISSUE THREAD

**Issue by arushsaxena1998** [mafredri/cdp#131]
I am running the following code for taking a full-page screenshot of a page.

package main

import (
	"fmt"

	"context"
	"io/ioutil"
	"time"
	"github.com/mafredri/cdp"
	"github.com/mafredri/cdp/protocol/emulation"
	"github.com/mafredri/cdp/protocol/page"
	"github.com/mafredri/cdp/rpcc"
)

func main() {
	ctx, cancel := context.WithTimeout(context.Background(), time.Hour * 1)
	defer cancel()

	// Initiate a new RPC connection to the Chrome DevTools Protocol target.
	conn, err := rpcc.DialContext(ctx, "ws://172.20.10.2:4444/session/aaa9809d40d2ea4b27bd9ee8daff5b65/se/cdp")
	if err != nil {
		fmt.Println(err)
	}
	defer conn.Close() // Leaving connections open will leak memory.

	c := cdp.NewClient(conn)
	
	emulationArgsPointer := emulation.NewSetDeviceMetricsOverrideArgs(645,9651,2.0,false)
	fmt.Println(emulationArgsPointer)
	emulation:= c.Emulation.SetDeviceMetricsOverride(ctx,emulationArgsPointer)
	
	fmt.Println(emulation)
	// Capture a screenshot of the current page.
	screenshotName := "screenshot.jpg"
	screenshotArgs := page.NewCaptureScreenshotArgs()
	screenshot, err := c.Page.CaptureScreenshot(ctx, screenshotArgs)
	if err != nil {
		fmt.Println(err)
	}
	if err = ioutil.WriteFile(screenshotName, screenshot.Data, 0644); err != nil {
		fmt.Println(err)
	}
	
}

It is giving me following error -> cdp.Emulation: SetDeviceMetricsOverride: rpc error: 'Emulation.setDeviceMetricsOverride' wasn't found (code = -32601)
cdp.Page: CaptureScreenshot: rpc error: 'Page.captureScreenshot' wasn't found (code = -32601)

Chrome Version used:: 101

**Comment by mafredri** [comment]
The example you posted works fine for me (Chromium 101.0.4936.0). Output:

```
&{645 9651 2 false <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil>}
<nil>
```

I'm curious how you got the websocket URL? I'm not familiar with that structure. If you're trying to use sessions, take a look at the `session` package.

**Comment by arushsaxena1998** [comment]
@mafredri I got the websocket URL by generating a session through selenium 4

**Comment by mafredri** [comment]
Ok, I think that might not be currently supported in this package, is it selenium specific or part of the devtools protocol? I will take a look and see if we can support it when I have some time.

For now, I'd recommend looking at the [Incognito example](https://pkg.go.dev/github.com/mafredri/cdp#example-package-Incognito) for how how to use sessions.

The URL we're using there looks a bit different, and we're fetching it directly from Chrome:

```
❯ curl -s http://localhost:9222/json/version | jq -r .webSocketDebuggerUrl
ws://localhost:9222/devtools/browser/637f3792-4870-42f7-adea-47dfe5f43a09
```

**Comment by arushsaxena1998** [comment]
we can close this issue. websocket debugger url and chrome debugger url are different. worked for me
