### ISSUE TITLE
Attempted to use with node, too many chrome assumptions?

### ISSUE THREAD

**Issue by etep** [mafredri/cdp#132]
Attempted to use this to connect to a node process, but failed (was hoping to use cdp similarly to the npm package [chrome remote interface](https://github.com/cyrus-and/chrome-remote-interface)).

It seems that `devtoolCreateURL` suffixes the target URL with `/json/new` which is not expected by node. It might also be that my setup is wrong.

It would be useful if there was a node example.

**Comment by etep** [comment]
After some more digging, I believe this can be solved by using `devtool.List`.

Might we consider promoting something about this up into the README? We can close this issue otherwise.

**Comment by mafredri** [comment]
I created #133 which should help with discovery of correct usage when used with Node.js. Does this solve the issue? I'm a bit reluctant to adding Node.js tips to the README without it being officially supported / tested for.

That said, I'd love for Node.js to be officially supported, but I don't really have the bandwidth for that at the moment.

On that note, I always dreamed the `protocol` package could be generated for _specific_ use-cases, and versions of browsers/node/etc. Something like:

```
cdpgen -dest . -browser-proto <(curl http://localhost:9222/json/protocol) -js-proto ./cmd/cdpgen/protodef/js_protocol.json
```

Then the package would simply be `replace`d in `go.mod`. I never got around to it though and I haven't investigated what the optimal protocol package for Node.js looks like. For instance, do most of the functions (esp. from `js_protocol.json`) work in Node.js too?

Btw, the above command does work, but `cdpgen` needs a definition for the `binary` type. After adding that, you get an updated protocol package like pictured: 
<img width="756" alt="image" src="https://user-images.githubusercontent.com/147409/171995392-2cae1834-980f-4503-ba72-0486caa270e9.png">

**Comment by etep** [comment]
I think that is helpful (closing the issue).

As some context, I am hoping to use cdp to enable symbol files on preexisting node processes. In other words, suppose you have the following scenario: a node process (maybe running in prod) and you want to do some CPU profiling. You can restart your processes (this might not be nice) and add a command line arg. (e.g. `--perf-basic-prof-only-functions`) to get symbol files. But, through some clever use of the remote debugging protocol (e.g. cdp) and [https://github.com/mmarchini-oss/node-linux-perf](https://github.com/mmarchini-oss/node-linux-perf) you can get this symbol file to be generated dynamically w/out a process restart. The basic setup is to 1. compile the node-linux-perf code to a dynamic library, 2. use remote debugging protocol to bring that library in and execute its start method.

**Comment by mafredri** [comment]
That sounds cool @etep, feel free to open issues (or discussions) if you run into any problems with that. 👍🏻
