### ISSUE TITLE
Problem interacting with the remote debugging host over HTTP 

### ISSUE THREAD

**Issue by olliephillips** [mafredri/cdp#138]
Problem interacting with the remote debugging host over HTTP. With a headless instance of chrome running with remote debugging set I get this:

```devtool: CreateURL: Using unsafe HTTP verb GET to invoke /json/new. This action supports only PUT verb.```

I can't find an issue which relates to this, and there isn't much on the web about this specific error, other than this.

https://danielcompton.net/snippets/chrome-devtools-unsafe-http-verb

It would seem the verb change is to prevent CSRF attacks.  I'm unclear if all interaction with the debugger API is now a PUT request.

I'm on Mac, and the Chrome version is 111.0.5563.110

**Comment by olliephillips** [comment]
Just tested your dev branch and works great with my code @mafredri

**Comment by lfleal** [comment]
We ran into the same issue with 111.0.5563.110 on linux

**Comment by mafredri** [comment]
Thanks for testing @olliephillips! I just published v0.34.0.

@lfleal does release v0.34.0 fixe the issue for you?

**Comment by lfleal** [comment]
Looks like it, thanks for getting this out quickly.
