### ISSUE TITLE
Is This Repo Abandoned or Dead?

### ISSUE THREAD

**Issue by c9845** [mafredri/cdp#147]
Hello,
I have been using this repo for a long time.  Thank you for your work.  This package has worked very well.

There has not been a release since April 2023 and a lot has changed in chrome/chromium since then.  Is there a plan to update this repo or has it been abandoned at this time?

I am encountering issues using this package with the v128 version of chrome, I think due to how --headless is now treated (v128 uses --headless=new by default, previously the default was --headless=old).  I imagine a lot in the protocol has changed in the last year+ that may address this issue.

I would just like to know if I should consider forking this repo or put my attention to another similar package like chromedp.

**Comment by mafredri** [comment]
Hey @c9845, thanks for raising the question and happy to hear you've found the library useful.

I would say the package is neither abandoned nor dead, but unfortunately in somewhat of a maintenance mode as I haven't had much time or motivation to develop it further.

I do want to retain compatibility with latest Chrome so thanks for reporting the issue and I'll aim for a new release by the end of the week. (PS. Feel free to submit PRs if that's your yam.)

**Comment by c9845** [comment]
@mafredri Thanks for the update.  

I get the "maintenance mode" thing.  I have some projects in limbo too.  I didn't want to fork you package unless it was really dead since that always makes determining which package to use hard for other people (ex.: is the mafredri or the c9845 version more correct, updated, etc.).  

I look forward to seeing a new release.  If I can figure out how to work with `cdpgen` I will try to file a PR.

**Comment by mafredri** [comment]
Hey @c9845, I just released https://github.com/mafredri/cdp/releases/tag/v0.35.0, feel free to give it a spin.

I tried investigating the `--headless=new|old` issue, but I couldn't reproduce it. If the issue still persists, I'd appreciate if you could give me a way to reproduce it and I'll look into it.

(I tested both flags (old/new) with Chromium 127 and again after updating to 130.0.6692.0.)

**Comment by c9845** [comment]
@mafredri Thanks for the update.  I tried it, still getting errors, but that pointed me into a lot more digging around and I figure out my issue (the `--user-data-dir` used with `-headless` flag doesn't like an existing populated directory it seems, especially with `--headless=new`).  A bit odd, especially since the issue only seems to occur on Ubuntu and WSL, not Windows.

Anyway, thanks again for the update!
