### ISSUE TITLE
Extensions.loadUnpacked wasn't found

### ISSUE THREAD

**Issue by MarioSimou** [mafredri/cdp#148]
The error message appears straightforward, but I'm uncertain about what I might be doing wrong. According to the [documentation](https://chromedevtools.github.io/devtools-protocol/tot/Extensions/#method-loadUnpacked), I should use the absolute path of the extension. Therefore, I’m providing the absolute path to the extension's directory. However, I’m encountering the following error: `cdp.Extensions: LoadUnpacked: rpc error: 'Extensions.loadUnpacked' wasn't found (code = -32601)`. Any idea why? Is there anything that I need to enable?

```go
	var loadUnpackedArgs = extensions.NewLoadUnpackedArgs(
		"/home/projects/app/extension",
	)

	var loadUnpackedReply *extensions.LoadUnpackedReply
	var e error

	if loadUnpackedReply, e = c.Extensions.LoadUnpacked(bs.ctx, loadUnpackedArgs); e != nil {
		fmt.Printf("Error: %s", e.Error())
		return e
	}
```

**Comment by mafredri** [comment]
@MarioSimou another option is that this is being blocked by security settings, see: https://knowledge.workspace.google.com/kb/load-unpacked-extensions-000005962

**Comment by MarioSimou** [comment]
I'm using Chrome v127.0.6533.88. Indeed, I'm running on headless mode, but using the `--headless=new` flag.

**Comment by mafredri** [comment]
Alright, please update to v128 and make sure to enable the `--enable-unsafe-extension-debugging` flag as per docs: https://pkg.go.dev/github.com/mafredri/cdp#Extensions

**Comment by mafredri** [comment]
Closing due to age, feel free to reopen if this is still an issue and the aforementioned instructions didn't give a hint for solving the problem.
