### ISSUE TITLE
DevTools.Create() doesn't work with headless chromium

### ISSUE THREAD

**Issue by fd0** [mafredri/cdp#2]
Hi,

I'm trying to build a small tool that takes screenshots of a number of URLs. For that I'd like to use a headless chromium running on a server (without a display). I'd also like to do that with ~10 URLs in parallel, so I'd like to create 10 tabs in the browser and use them from different goroutines in parallel. 

With a GUI chromium that works great by creating a new "Page" for every goroutine:
```go
page, err := devt.Create(ctx)
```

However on a headless chromium that fails:
```
panic: target CreateURL: Could not create new page
```

Turns out that the code just requests `/json/new`, which [does not work on headless chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=626847). The way to go is to use `createTarget()` to create a new browsing environment, reference: https://groups.google.com/a/chromium.org/forum/#!topic/headless-dev/HLeIEn5V0DA

Can I do that already with `cdp`? I'm also willing to help implement this, if you guide me through the code base a bit :)

**Comment by mafredri** [comment]
Hi @fd0, and thanks for bringing this to my attention! I was unaware that headless is yet to implement the `/json/new` endpoint.

This is also the first time I saw the `/devtools/browser` endpoint, I'll need to put some thought into how best to implement this, perhaps in the `devtool` package.

For now, you should be able to accomplish what you want by connecting to `/devtools/browser` over websocket and using the `Target` domain. The following example only needs `Target.createTarget` to be implemented and should do what you want:

```go

func createPage(ctx context.Context, devtoolURL, pageURL string) (*devtool.Target, error) {
	conn, err := rpcc.DialContext(ctx, "ws://"+devtoolURL+"/devtools/browser")
	if err != nil {
		return nil, err
	}
	defer conn.Close()

	c := cdp.NewClient(conn)

	// Create new target, might not be immediately available.
	new, err := c.Target.CreateTarget(ctx, cdpcmd.NewTargetCreateTargetArgs(pageURL))
	if err != nil {
		return nil, err
	}

	devt := devtool.New("http://" + devtoolURL)
	for {
		// Fetch list until the target is available.
		list, err := devt.List(ctx)
		if err != nil {
			return nil, err
		}
		for _, p := range list {
			if p.ID == string(new.TargetID) {
				return p, nil
			}
		}
	}
}

func Example() {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	page, err := createPage(ctx, "127.0.0.1:9222", "about:blank")
	if err != nil {
		panic(err)
	}

	conn, err := rpcc.DialContext(ctx, page.WebSocketDebuggerURL)
	if err != nil {
		panic(err)
	}
	defer conn.Close()

	c := cdp.NewClient(conn)

	// Do stuff with c ...
}
```

I tried some other approaches, but it seems that only `createTarget` is implemented on the headless build I'm running. This should be easy to simplify greatly when other Target-methods are available, for example:

```go
conn, err := rpcc.DialContext(ctx, "ws://127.0.0.1:9222/devtools/browser")
if err != nil {
	panic(err)
}
defer conn.Close()

c := cdp.NewClient(conn)
newTarget, err := c.Target.CreateTarget(ctx, cdpcmd.NewTargetCreateTargetArgs("https://www.google.com"))
if err != nil {
	panic(err)
}

err = c.Target.ActivateTarget(ctx, cdpcmd.NewTargetActivateTargetArgs(newTarget.TargetID))
if err != nil {
	panic(err)
}

attached, err := c.Target.AttachToTarget(ctx, cdpcmd.NewTargetAttachToTargetArgs(newTarget.TargetID))
if err != nil {
	panic(err)
}

if !attached.Success {
	panic("failed to attach to target")
}
```

or

```go
// Enable target discovery (events).
err = c.Target.SetDiscoverTargets(ctx, cdpcmd.NewTargetSetDiscoverTargetsArgs(true))
if err != nil {
	panic(err)
}

newTarget, err := c.Target.CreateTarget(ctx, cdpcmd.NewTargetCreateTargetArgs("https://www.google.com"))
if err != nil {
	panic(err)
}

page, err := created.Recv()
if err != nil {
	panic(err)
}

log.Println(page.TargetInfo)
```

**Comment by mafredri** [comment]
PS. If you should have an active connection to a page and you simply want to create a new one, you should also be able to use the `Target` domain with it straight, without connecting to the `/devtools/browser` endpoint.

I believe that when connected to a page, the `Target` endpoint will support more features than when connected to `/devtools/browser` (e.g. my failed attempts above should work, maybe?).

**Comment by mafredri** [comment]
> I'm also willing to help implement this, if you guide me through the code base a bit :)

Ah silly me, I got a bit carried away when you introduced the problem 😅. I would be happy to accept contributions though, so here a lay of the land in the form of bullet-points:

Non-generated code:
* The packages `devtool` and `rpcc` are the only non-generated packages, the rest are mostly generated by `cmd/cdpgen`
* `rpcc` is the RPC client that sends commands, receives responses / events and distributes them appropriately
    * The generated code mostly just calls `rpcc.Invoke` (for commands) or `rpcc.NewStream` (for events)
* `devtool` provides convenient features for managing the browser instance (creating tabs, browser info, etc)
* `cdptype` contains some non-generated code in `util.go` and `misc.go` to provide some convenient features (there's lots of room for improvement here, given a better understanding of all the types and their purpose)

Generated code:
* Has the header `// Code generated by cdpgen; DO NOT EDIT!`
* `cdp` provides a CDP client with all CDP domains accessible via it
    * Can provide functions / features that improves ergonomics when working with CDP (only has `ErrorCause` atm)
* `cdpcmd` contains all the commands / arguments that can be executed over CDP (browser does not necessarily implement them)
* `cdpevent` is like `cdpcmd` but for CDP events
* `cdptype` is types used by commands and events
* `cdpdom` is an implementation detail, implements the CDP domains (interfaces) defined in `cdp`

I'm not sure if this was of much use as guidance, but hope it can be useful for you. I realize this should be documented better, part of the reason for writing this down here was as a first step toward that goal and as an exercise for myself 😄.

**Comment by fd0** [comment]
Thank you very much for the comprehensive answers! It actually sounds like a lot more work than I expected, so if you have some time to implement it please go ahead :)

**Comment by mafredri** [comment]
You're welcome! Let me know if you have any trouble with the `createPage` example above. No worries, I'll try to get this implemented soon 😄.

I think the for loop in the example could be removed, though:

```go
// Fetch list until the target is available.
list, err := devt.List(ctx)
if err != nil {
	return nil, err
}
for _, p := range list {
	if p.ID == string(newTarget.TargetID) {
		return p, nil
	}
}
return nil, errors.New("createPage: could not create page")
```

The reason I put it there was as a precaution because I did not know the reason I had to fetch the list. But it seems it might be a bug in headless chrome, and fetching the list makes the page *available*, so the for loop might be unnecessary. The WebSocket URL can be constructed manually (e.g. `"ws://localhost:9222/devtools/page/" + string(newTarget.TargetID)`), but the page will not be available before the call to `list`. On the other hand, maybe sleeping would do the same?

**Comment by mafredri** [comment]
Relevant issue regarding the need to call `list` after `Target.createTarget`: https://bugs.chromium.org/p/chromium/issues/detail?id=704503

**Comment by mafredri** [comment]
@fd0 you should now be able to use `devt.Create()` and `devt.CreateURL()` with Headless Chrome! 🎉 

Please let me know if there are any problems 😄.

**Comment by fd0** [comment]
Thanks! I'll give it a try. Is there a gentle introduction to the capabilities and the protocol that I can use to get an overview?

**Comment by mafredri** [comment]
> Is there a gentle introduction to the capabilities and the protocol that I can use to get an overview?

@fd0 what kind of introduction would be helpful? Here's what I can think of of the top of my head:

You should be able to get an idea of what the protocol is capable of from this projects [GoDoc](https://godoc.org/github.com/mafredri/cdp) reference by taking a look at the CDP domains exposed by [Client](https://godoc.org/github.com/mafredri/cdp#Client). There are at least three domains that are of interest for most use-cases: [DOM](https://godoc.org/github.com/mafredri/cdp#DOM), [Network](https://godoc.org/github.com/mafredri/cdp#Network) and [Runtime](https://godoc.org/github.com/mafredri/cdp#Runtime).

You can also take a look at the [Advanced Example](https://godoc.org/github.com/mafredri/cdp#ex-package--Advanced) which covers commands, events, navigation, exception handling (js), network request error handling, evaluation (js `eval`) and dom manipulation. The (not advanced) [Example](https://godoc.org/github.com/mafredri/cdp#ex-package) is basically the same as in the README.

For more information on the Chrome Debugging Protocol there are a few resources that are of interest:
* [Chrome Debugging Protocol](https://developer.chrome.com/devtools/docs/debugger-protocol) (official page)
* [Chrome Debugging Protocol Viewer](https://chromedevtools.github.io/debugger-protocol-viewer/) displays all he domains, methods, events and types used by CDP
* [RemoteDebug](http://remotedebug.org/) is an initiative to bring remote debugging (e.g. CDP) to all modern browsers
* [RemoteDebug Protocol Compatibility Tables](https://compatibility.remotedebug.org/) for a an idea what's supported between different browsers

Do let me know if you have any ideas on how to improve the documentation. I want this project to be easy to get started with, without prior knowledge of CDP!

**Comment by mafredri** [comment]
As a final note: since the Chrome DevTools (`Cmd+Opt+I`) does everything over the Chrome Debugging Protocol, you can essentially do all the things that are possible via the Chrome DevTools 😄.

**Comment by fd0** [comment]
Thanks a lot for all the pointers!
