### ISSUE TITLE
Try to generate new protocol, getting an error

### ISSUE THREAD

**Issue by matthewmueller** [mafredri/cdp#21]
Running `go version go1.9rc1 darwin/amd64`

```
cdpgen -dest-pkg github.com/mafredri/cdp     -browser-proto $GOPATH/src/github.com/mafredri/cdp/cmd/cdpgen/protodef/browser_protocol.json     -js-proto $GOPATH/src/github.com/mafredri/cdp/cmd/cdpgen/protodef/js_protocol.json
...writing...
2017/07/31 11:59:14 /Users/matt/go/src/github.com/mafredri/cdp/protocol/page/types19.go:56:19: expected type, found '='
/Users/matt/go/src/github.com/mafredri/cdp/protocol/page/types19.go:82:14: expected type, found '='
/Users/matt/go/src/github.com/mafredri/cdp/protocol/page19.go:10:23: expected type, found '='
/Users/matt/go/src/github.com/mafredri/cdp/protocol/page19.go:15:18: expected type, found '='
2017/07/31 11:59:14 exit status 2
```

Any ideas? :-)

**Comment by matthewmueller** [comment]
Oh one other thing I had to change in `./update.sh`.

```diff
+ base -d
- base -D
```

Using linux's base64 executable:`/usr/local/opt/coreutils/libexec/gnubin/base64`

**Comment by mafredri** [comment]
`cdpgen` has to be built by go 1.9, and also `goimports`. Good to know about Linux, I've only used this on macOS so far 😁.

Btw, I'm on vacation this week (back by next weekend) so apologies if I'm slow at responding. Am also computerless 😝.

**Comment by matthewmueller** [comment]
Sorry for interrupting your vacation! Have a great trip :-)

Hmm, sounds like I'm doing it correctly, I'll try again in a bit!

**Comment by mafredri** [comment]
> Sorry for interrupting your vacation! Have a great trip :-)

Thanks, and no worries, I didn't mind :-)!

> Hmm, sounds like I'm doing it correctly, I'll try again in a bit!

Did it work out? Here are steps that I believe should work:

```console
$ go1.9rc1 get -u golang.org/x/tools/cmd/goimports
$ cd $GOPATH/src/github.com/mafredri/cdp/cmd/cdpgen && go1.9rc1 install
$ cdpgen -dest-pkg github.com/mafredri/cdp -browser-proto $GOPATH/src/github.com/mafredri/cdp/cmd/cdpgen/protodef/browser_protocol.json -js-proto $GOPATH/src/github.com/mafredri/cdp/cmd/cdpgen/protodef/js_protocol.json
```

If not, let me know what errors you're seeing after this!

**Comment by mafredri** [comment]
Closing this now seeing as Go 1.9 has already been out for a while. Feel free to re-open if you're still having issues with this. The base64 issue should be amended in 3d27c650341ffb17b6b65d59b6f4e43ad1b72000.
