### ISSUE TITLE
network.Response.Status  float64 and not int

### ISSUE THREAD

**Issue by shsms-i2i** [mafredri/cdp#27]
Hi,

First of all, thanks for a great library!

Why is response status a float64 and not int like it is in the native http.Response.StatusCode?

If it is not going to change to int,  would you mind adding a comment before the field explaining the reason?

Thanks

**Comment by mafredri** [comment]
Hi @shsms-i2i, thanks for the kind words.

The reason it's a `float64` is that that's how it's defined in the protocol definition ([js_protocol.json#L1387](https://github.com/mafredri/cdp/blob/df4f185c948392f02ed00b4cf5884b9665ab984e/cmd/cdpgen/protodef/js_protocol.json#L1387)) and `network.Response` is generated from that definition. Type `number` translates into `float64` whereas `integer` translates into `int`.

You're right that this is confusing and impractical. I'll open up an issue upstream regarding this, and if it can't be fixed there, for whatever reason, I'll look into patching it here.

**Comment by shsms-i2i** [comment]
Hey, thank you very much!  I'm assuming I would have to wait a while before stable chrome starts to support it?  I will keep track.

**Comment by mafredri** [comment]
I don't think you have to wait @shsms-i2i, even though this previously was stored as a double, I doubt there have ever been cases that it isn't an int because that would go against the HTTP specification. As long as Chrome keeps sending `400` instead of `400.123` this change will not break anything 🙂!
