### ISSUE TITLE
How to catch Headless Chrome error: VALIDATION_ERROR_MESSAGE_HEADER_UNKNOWN_METHOD

### ISSUE THREAD

**Issue by psykomo** [mafredri/cdp#29]
Hi, 
Sometimes, headless chrome produced Invalid message: VALIDATION_ERROR_MESSAGE_HEADER_UNKNOWN_METHOD error. I noticed that this error happened when my laptop went standby and on again several time while i kept the headless chrome up. 

I tried to listen to event produced by c.Runtime.ExceptionThrown, but it did not produce above error.

Is there any way to listen to this type of error?

Thanks!

**Comment by mafredri** [comment]
Where does Chrome produce this error message? I'm not sure it's catchable over the protocol but you could try the `Log.EntryAdded` or `Runtime.ConsoleAPICalled` events (remember to enable the domains too).

Ultimately I would recommend opening up an issue at [ChromeDevTools/devtools-protocol](https://github.com/ChromeDevTools/devtools-protocol/issues), they might have a better idea if it can be caught or not.

**Comment by psykomo** [comment]
Thanks for the tips! I will try the log and the runtime first before asking the ChromeDevTools guys.

**Comment by mafredri** [comment]
I’m curious, did you manage to solve this @psykomo?

**Comment by psykomo** [comment]
Not yet. I decided to skip it and tackle other issues. But, once I get back to solve this, I will write the result.

**Comment by mafredri** [comment]
Closing this due to age, hoping this issue no longer haunts you 😄.
