### ISSUE TITLE
Documentation for DevTool

### ISSUE THREAD

**Issue by mattcodez** [mafredri/cdp#30]
Hi, I'm trying to understand the purpose and use of methods like `devtool.New(...)` and `Get()`, `Create()` etc. There doesn't seem to be any information either in the CDP GoDoc or the official DevTools Protocol Viewer. Where can I get more information on how to use these methods? Thanks.

**Comment by mafredri** [comment]
The package has it's own GoDoc (https://godoc.org/github.com/mafredri/cdp/devtool), the cdp docs only mention it in passing. The devtool package is (at least currently) just a convenient wrapper around the /json/{new,list,etc...} endpoints for the browser (via http). It's functionality could also be replicated with the Target domain of cdp. To use the target domain to control the browser, you could connect to `rpcc.DialContext(ctx, "ws://localhost:9222/devtools/browser")`.

Let me know if you have further questions 🙂!

**Comment by mattcodez** [comment]
Awesome, thanks! I'm trying to figure out how to do concurrent jobs. Right now if I run two requests at once using the example code, `pt.WebSocketDebuggerURL` comes back empty for the 2nd request if sent before the 1st finishes. I'm guessing I need to program it such that there is only one connection via `New()` that is used for all requests and then each request has its own `Create()` associated with it.

**Comment by mafredri** [comment]
I see you closed this issue, I hope this means you managed to solve / work around the issue!

> Right now if I run two requests at once using the example code, pt.WebSocketDebuggerURL comes back empty for the 2nd request if sent before the 1st finishes

I don't quite follow what's happening, could you elaborate on this? Can't help but wonder if it's something that could be improved upon.

>  I'm guessing I need to program it such that there is only one connection via New() that is used for all requests and then each request has its own Create() associated with it.

Give the quirkiness of the `/json` endpoint, this sounds like the best approach. I could add a mutex to `devtool.DevTools` though, to avoid concurrent calls to e.g. Create, I'm guessing that would help here?
