### ISSUE TITLE
Opening multiple browser tabs?

### ISSUE THREAD

**Issue by songlong** [mafredri/cdp#34]
how to open mulit browser tab?
I should call which function?

**Comment by mafredri** [comment]
I'm not sure I understand, could you clarify what it is you want to do?

I recommend checking out the package documentation for [cdp](https://godoc.org/github.com/mafredri/cdp) and [devtool](https://godoc.org/github.com/mafredri/cdp/devtool), there are some examples on how to use the packages.

**Comment by songlong** [comment]
spider many urls by created a connect in 9222 port, not to create many connect.
can you help to get  some examples?
Or I need build much context by page.NewNavigateArgs("https://google.com")

**Comment by mafredri** [comment]
Are you looking to spider them simultaneously (multiple tabs) or one at a time (single tab)?

If you're looking to do this simultaneously, there are currently two options:

1. Use `devtool` to create multiple pages and create a separate `rpcc` connection to each one
2. Use the `Target` domain to create and connect to multiple targets and communicate via `SendMessageToTarget` and `ReceivedMessageFromTarget`
  * You can read more about this in #33 

I'm currently working on something to improve the usage of the `Target` domain but it's not ready yet.

**Comment by songlong** [comment]
thanks!
when url finish html loading, how to get headers of netowrk response

**Comment by mafredri** [comment]
For network headers you need to enable events for the `Network` domain and listen to the events.
