### ISSUE TITLE
Is there a way to simulate click event?

### ISSUE THREAD

**Issue by medcl** [mafredri/cdp#35]
Like click the checkbox and submit a form, 
i didn't find a example. is it already implemented or not possible to do?
Thanks.

**Comment by mafredri** [comment]
Yes it's possible using the Input domain.

Here's an example how you could issue a synthetic click event in the browser (at coordinate (100, 100)):

```go
clickArgs := input.NewDispatchMouseEventArgs("mousePressed", 100, 100).
	SetButton("left").
	SetClickCount(1)
err = c.Input.DispatchMouseEvent(ctx, clickArgs)
if err != nil {
	return err
}
clickArgs.Type = "mouseReleased"
err = c.Input.DispatchMouseEvent(ctx, clickArgs)
if err != nil {
	return err
}
```

When it comes to submitting forms it's probably easiest to use JavaScript. As an example, this is something I've used in the past:

```go
func submitForm(ctx context.Context, c *cdp.Client, expression string) error {
	domContentEventFired, err := c.Page.DOMContentEventFired(ctx)
	if err != nil {
		return err
	}
	defer domContentEventFired.Close()

	_, err = c.Runtime.Evaluate(ctx, &runtime.EvaluateArgs{
		Expression: expression,
	})
	if err != nil {
		return err
	}

	_, err = domContentEventFired.Recv()
	return err
}
```

It evaluates the JS (for form submission) and waits for the new page to load. Usage would then look like:

```go
err = submitForm(ctx, c, `document.getElementById('mainform').submit()`)
if err != nil {
	return err
}
```

But this all just boils down as to how you wish to use the Chrome DevTools Protocol, it's very powerful but also low-level and not that well documented 😄.
