### ISSUE TITLE
Autosizing when printing to PDF

### ISSUE THREAD

**Issue by mattcodez** [mafredri/cdp#37]
If I print to PDF from desktop Chrome, the PDF automatically sizes to fit the content being printed. When using cdp to print from headless Chrome, `PrintToPDFArgs.PaperWidth` and `PrintToPDFArgs.PaperHeight` are set by default. This can cause large white margins to be added to pages that don't fit this dimension or aspect ratio. I'm sure it could be fixed by setting these values correctly, but it would be great if they could somehow not be used at all like is done on desktop. Is there a way around this? Thanks.

**Comment by mafredri** [comment]
Unfortunately there is no way to remove/unset those defaults, they are defined in the protocol and when no values are provided for Width/Height, the defaults are assumed by Chrome :/. I tried setting these values to 0 in hopes of enabling some kind of automatic detection, but Chrome does not consider it a valid input.

So it seems the only option left is to either adjust page height/width or scale when printing.

**Comment by mattcodez** [comment]
Thanks for the reply. It appears this may be a protocol level limitation/bug: https://bugs.chromium.org/p/chromium/issues/detail?id=724160

**Comment by mafredri** [comment]
Nice find, thanks for posting the link. I was thinking of injecting e.g. `@page {size: A4;}` as a potential solution, but I didn't know exactly what your use-case was. Judging from the chromium issue, that wouldn't have worked though.

**Comment by mafredri** [comment]
This was fixed in https://chromium.googlesource.com/chromium/src.git/+/665cdea2f5f29e166ad455b5021154456944fcbc.

The latest version of Chrome/Chromium (Canary) should support CSS page sizing by setting `PreferCSSPageSize` when printing.

The protocol definition was updated in 574706e22295ec86605706fd90902b54fcafd1b8.
