### ISSUE TITLE
Request interception not working for all requests

### ISSUE THREAD

**Issue by zfLQ2qx2** [mafredri/cdp#40]
Just curious - I have a working request interception function:

        url := "*"
        err = c.Network.SetRequestInterception(ctx, network.NewSetRequestInterceptionArgs([]network.RequestPattern{network.RequestPattern{URLPattern: &url}}))
        if err != nil {
                log.Fatal("SetRequestInterception error:", err.Error())
        }

        go func() {
                requestIntercepted, err := c.Network.RequestIntercepted(ctx)
                if err != nil {
                        log.Fatal(err)
                }
                defer requestIntercepted.Close()
                for {
                        select {
                        case <-requestIntercepted.Ready():
                                reply, err := requestIntercepted.Recv()
                                if err != nil {
                                        log.Fatalf("requestIntercepted failed: %s", err)
                                        continue
                                }
                                data, err := json.Marshal(reply)
                                if err != nil {
                                        log.Fatalf("Error marshaling response: %s", err)
                                        continue
                                }
                                log.Printf("requestIntercepted: %s", data)
                                err = c.Network.ContinueInterceptedRequest(ctx, network.NewContinueInterceptedRequestArgs(reply.InterceptionID))
                                if err != nil {
                                        log.Fatalf("ContinueInterceptedRequest: %s", err)
                                        continue
                                }
                                continue
                        }
                }
        }()

And I am loading a minimal html page:

https://www.sitepoint.com/a-minimal-html-document-html5-edition/

When I load this page I only receive requestIntercepted for the html file and favicon.ico - the intercept event for style.css never fires that I can see. I see the style.css request hit my test server and I see a ResponseReceived event for it.

Even more odd, if there is a problem with the stylesheet like it not existing, then I see neither the requestIntercepted or ResponseReceived events.

I thought that maybe I was dropping or consuming events inadvertently so I setup a second test file with a handful of css files listed, and I see the same behaviors for all of them - never a requestIntercepted event, every request hits the backend, but I only receive ResponseReceied events for the ones that exist. 

If I open chrome devtools and reload the page, I see full details of the requests for all the stylesheets regardless of their existence.

If I enable RequestWillBeSent and LoadFailed/LoadFinished events then I see those for all stylesheets.

Any idea what is the cause of this behavior? I see it with both Chrome 64 and Chrome 66

**Comment by mafredri** [comment]
I tested on macOS with Chrome Beta (64) and Chrome Canary (65) (both with `--headless`) and cannot reproduce the issue. For some reason request interception doesn't work for me on macOS without headless, but I haven't bothered to figure out why.

Some thoughts:

* Are you serving html from disk (`file:///`)? If yes, try to put it behind a server.
* Have you tried with `--headless`?
* Have you tried disabling cache (`c.Network.SetCacheDisabled(ctx, network.NewSetCacheDisabledArgs(true))`)?

Sidenote: Maybe you are aware, but using the `.Ready()` channel is not required in this case. It's a good way to save on goroutines though! E.g. when checking multiple events or when synchronizing events via `cdp.Sync`. 😄

**Comment by mafredri** [comment]
PS. I recommend setting up logging so that you can verify if you're missing events: [Example (Logging)](https://godoc.org/github.com/mafredri/cdp#example-package--Logging).

**Comment by zfLQ2qx2** [comment]
@mafredri Guilty, I am on MacOS and I was omitting the "--headless" option for perceived convenience. I added the --headless flag and now I see intercepts for all the style sheets. I still don't see RequestResponses for the ones that get 404 responses, but I think that is more of a chrome on MacOS issue and not my misusing cdp - as long as I get the LoadFailed events I can make do.

For the go routines my plan is to have one routine that navigates and analyses the DOM, and a second routine to monitor events (close dialogs, kill pop-ups, watch for browser crashes, etc.) Does that seem reasonable? Or is there a better way?

**Comment by mafredri** [comment]
Yeah, not sure if there should be a ResponseReceived in that case. Probably best to ask the good folks over at the chrome-debugging-protocol mailing list.

> For the go routines my plan is to have one routine that navigates and analyses the DOM, and a second routine to monitor events (close dialogs, kill pop-ups, watch for browser crashes, etc.) Does that seem reasonable? Or is there a better way?

I think it sounds fine 😄.

**Comment by zfLQ2qx2** [comment]
Great, good to know I'm on the right track. That mailing list is surprisingly low volume considering how many people have an interest in this, not a lot of interaction so far. I may try doing a bug report, they seem to get a lot more attention.

**Comment by mafredri** [comment]
Mm, it seems to vary quite a lot. There's also a ML for headless which you could check out: https://groups.google.com/a/chromium.org/forum/#!forum/headless-dev
