### ISSUE TITLE
Network GetResponseBody returns: "No resource with given identifier" after ResponseReceived

### ISSUE THREAD

**Issue by songlong** [mafredri/cdp#42]
when monitor network event, it willl happend 	
 cdp.Network: GetResponseBody: rpc error: No resource with given identifier found (code = -32000)

code:
_, err = c.Network.GetResponseBody(ctx, &network.GetResponseBodyArgs{RequestID: xxs.RequestID})
	//fmt.Println("resp", resp)
	fmt.Println("xxs.RequestID: ", xxs.RequestID)
	if err != nil {
		fmt.Println("------------------------sss", err, xxs.RequestID)
		return cret, err
	}

**Comment by songlong** [comment]
had join in ResponseReceived, but it happened concurrency call by chrome spider 10 urls.

	// Enable events on the Page domain, it's often preferrable to create
	// event clients before enabling events so that we don't miss any.
	if err = c.Page.Enable(ctx); err != nil {
		return cret, err
	}

	if err = c.DOM.Enable(ctx); err != nil {
		return cret, err
	}
	
	if err = c.Network.Enable(ctx, network.NewEnableArgs()); err != nil {
		return cret, err
	}

	networkEvent, err := c.Network.ResponseReceived(ctx)
	if err != nil {
		return cret, err
	}

**Comment by mafredri** [comment]
It looks like someone else has run into this as well: https://github.com/ChromeDevTools/devtools-protocol/issues/64

> [...] Usually the response body comes back fine no problem. However, if the response is a downloaded file, it seems getResponseBody returns an error, 'No data found for resource with given identifier'. [...]

Does this sound similar to your problem, @songlong?

**Comment by mafredri** [comment]
Also here: https://github.com/ChromeDevTools/devtools-protocol/issues/44.

It looks like [waiting for `Network.LoadingFinnished`](https://github.com/ChromeDevTools/devtools-protocol/issues/44#issuecomment-320127404) might help.

**Comment by mafredri** [comment]
Hope you've found a solution by now! Closing as this is related to protocol usage.
