### ISSUE TITLE
Emulation.setNavigatorOverrides wasn't found

### ISSUE THREAD

**Issue by varashellov** [mafredri/cdp#43]
Hello!
I'm trying to override Platform, but get a error. 

```
em := emulation.NewClient(conn)
emErr := em.SetNavigatorOverrides(ctx, &emulation.SetNavigatorOverridesArgs{Platform: "Win32",})
if emErr != nil {
    panic(emErr)
}

panic: cdp.Emulation: SetNavigatorOverrides: rpc error: 'Emulation.setNavigatorOverrides' wasn't found (code = -32601)
```
Google Chrome 62.0.3202.89

**Comment by mafredri** [comment]
Usually this kind of error means one of:

* Your version of Chrome is too old and does not support the command
* This command has been renamed or removed
* The command is only supported in Headless / non-headless

In this case I believe it’s the first option. I recommend checking the protocol history in situations like these. You can find the relevant entry here: https://github.com/ChromeDevTools/devtools-protocol/blob/master/changelog.md#roll-protocol-to-r501229

**Comment by varashellov** [comment]
Exactly! With chrome 63 works. Thanks.
