### ISSUE TITLE
Change page viewport size

### ISSUE THREAD

**Issue by s3rj1k** [mafredri/cdp#46]
Please provide example with ability to screenshot view port with custom size.

**Comment by peterheb** [comment]
What works for me is adding:

`c.Emulation.SetDeviceMetricsOverride(ctx, emulation.NewSetDeviceMetricsOverrideArgs(1280, 1024, 1, false))`

after `c := cdp.NewClient(conn)` in the example in the README.

**Comment by s3rj1k** [comment]
@peterheb is there any way of determining actual page size(height)? 
needed for full page screenshot

**Comment by peterheb** [comment]
I am honestly not an expert at using CDP, but I tried calling:

```
lay, err := c.Page.GetLayoutMetrics(ctx)
fmt.Printf("Layout: %+v\n", *lay)
```

And it looks like `lay.ContentSize.Height` has something resembling the size of the page:

```
Layout: {LayoutViewport:{PageX:0 PageY:0 ClientWidth:1280 ClientHeight:1024}
VisualViewport:{OffsetX:0 OffsetY:0 PageX:0 PageY:0 ClientWidth:1280 ClientHeight:1024 Scale:1} 
ContentSize:{X:0 Y:0 Width:1280 Height:5837}}
```

**Comment by mafredri** [comment]
@s3rj1k regarding the original issue about providing an example. The purpose of this package is not to teach the entire CDP protocol, it's hyooooge (and documentation is sparse). That being said, I'm very open to including useful examples in this repo, PRs are welcome.

Most of the time I don't know the answer to doing X with the protocol either, but usually a bit of search + experimentation can bring an answer.

A good place to ask these types of questions is the [CDP mailing list](https://groups.google.com/forum/#!forum/chrome-debugging-protocol) or the [headless mailing list](https://groups.google.com/a/chromium.org/forum/#!forum/headless-dev) (if it's headless related). They are far more knowledgeable than I 😄.

Thanks for chipping in @peterheb, it's appreciated ☺️.

**Comment by s3rj1k** [comment]
in addition to what @peterheb suggested

this construct should be used:

```
	layout, _ := c.Page.GetLayoutMetrics(ctx)

	screenshotArgs := page.NewCaptureScreenshotArgs().
		SetFormat("png").
		SetClip(
			page.Viewport{
				X:      0,
				Y:      0,
				Width:  layout.ContentSize.Width,
				Height: layout.ContentSize.Height,
				Scale:  1,
			})

	screenshot, _ := c.Page.CaptureScreenshot(ctx, screenshotArgs)
```

**Comment by mafredri** [comment]
Thanks for the update @s3rj1k, I've been thinking about some more advanced examples (e.g. multiple tabs, incorporating the `session` package, etc) and perhaps this could be included there.

I've also been prototyping a `browsertool` package (it's been on-hold because I split part of it into `session`), perhaps this could be part of it as I think it's a pretty common use-case. If you're interested, you can have a look at the WIP [godoc for browsertool](https://gist.github.com/mafredri/4010764a9c7235ab27a6c96f9155fbd9).

**Comment by s3rj1k** [comment]
Hi @mafredri 

I actually have some issues with multitab workers, because of async nature of protocol, new tabs are opened faster than i do screenshot and close old ones.

This is issue as chrome tends to leak memory, would be nice to see some multitabls example with some mutexes to keep tab count constant, IE tabs are equal to number of workers.

If you can draft something up, i can test i production code.

**Comment by s3rj1k** [comment]
I actually use this kind of approach, noticed that chrome starts to crush after a few dozens of screenshots. : (
So i decided to spawn a pool of chromes instead and use one debug protocol per screenshot.
Still have some issues with this :)

Will write separate issue on them so other people will also benefit on this.

**Comment by s3rj1k** [comment]
closing this one, example would go like this

```
	err = c.Emulation.ClearDeviceMetricsOverride(ctx)
	if err != nil {
		return err
	}

	err = c.Emulation.SetDeviceMetricsOverride(ctx,
		&emulation.SetDeviceMetricsOverrideArgs{
			Width:             windowWidth,
			Height:            windowHight,
			DeviceScaleFactor: 1,
			Mobile:            false})
	if err != nil {
		return err
	}
...

	layout, err := c.Page.GetLayoutMetrics(ctx)
	if err != nil {
		return err
	}

...

	screenshotArgs := page.NewCaptureScreenshotArgs().
		SetFormat("png").
		SetClip(
			page.Viewport{
				X:      0,
				Y:      0,
				Width:  layout.ContentSize.Width,
				Height: layout.ContentSize.Height,
				Scale:  1,
			})
...

	screenshot, err := c.Page.CaptureScreenshot(ctx, screenshotArgs)
	if err != nil {
		return err
	}

```

**Comment by mafredri** [comment]
@s3rj1k thanks for the code, I'll try to incorporate it into an example in the future ^_^!
