### ISSUE TITLE
getting error with Security.SetIgnoreCertificateErrors

### ISSUE THREAD

**Issue by s3rj1k** [mafredri/cdp#47]
`2018/03/14 13:39:48 cdp.Security: SetIgnoreCertificateErrors: rpc error: 'Security.setIgnoreCertificateErrors' wasn't found (code = -32601)`

using this code:

```
	err = c.Security.SetIgnoreCertificateErrors(ctx, &security.SetIgnoreCertificateErrorsArgs{Ignore: true})
	if err != nil {
		return err
	}
```

what I am doing wrong here?

**Comment by mafredri** [comment]
RPC errors come from Chrome, meaning Chrome doesn't support that method.

It was added in version 65, so you must either update Chrome or use the deprecated method: `SetOverrideCertificateErrors`.

**Comment by s3rj1k** [comment]
WOW, thanks for so quick response, indeed, it is chrome version problem.

Thanks a lot :)
