### ISSUE TITLE
Is remote-debugging-socket-fd supported?

### ISSUE THREAD

**Issue by s3rj1k** [mafredri/cdp#49]
using socket instead of tcp ports?

**Comment by mafredri** [comment]
Interesting, I wasn't aware that it's a possibility. However, I believe this should work quite nicely if you provide a custom dialer for `rpcc` that simply returns the file descriptor.

```go
fdDialer := rpcc.WithDialer(func(_ context.Context, _ string) (io.ReadWriteCloser, error) {
	return myFd, nil
})
conn, err := rpcc.DialContext(ctx, "", fdDialer)
```

Managing the fd needs to be done when Chrome is launched, I believe [this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=624837#c19) on the chromium bug tracker might be of help.

Let me know if there are any issues, good luck!

**Comment by s3rj1k** [comment]
hmm, that looks overcomplicated :)

ended up using

```
func GetFreePort() (int, error) {
	addr, err := net.ResolveTCPAddr("tcp", "[::]:0")
	if err != nil {
		return 0, err
	}

	l, err := net.ListenTCP("tcp", addr)
	defer l.Close()
	if err != nil {
		return 0, err
	}

	return l.Addr().(*net.TCPAddr).Port, nil
}
```
