### ISSUE TITLE
Strange issue with screenshotting dynamic websites

### ISSUE THREAD

**Issue by s3rj1k** [mafredri/cdp#50]
Using this code I can actually screenshot properly most of web pages
https://gist.github.com/s3rj1k/0fc459f9c6aa7db42283b805c509e007

but it fails with pikabu.ru, output is somehow stacked

proper screenshot can be seen in https://dehtml.com/https://pikabu.ru
using phantomjs

any ideas on how to fix this?

**Comment by mafredri** [comment]
Thanks for the sample code, I tried running it but I can't spot the problem. To me, the Chrome screenshot looks better / more correct (dehtml seems to render incorrectly):

<img width="1162" alt="screen shot 2018-03-17 at 14 59 27" src="https://user-images.githubusercontent.com/147409/37555681-f8445fde-29f3-11e8-9711-45bfd7f5564f.png">

What should I be looking for? PS. Using Chrome Beta (66) on macOS.

**Comment by s3rj1k** [comment]
@mafredri bottom page, for me site header is doubled
proper footer should look like this
https://prnt.sc/isg5t0

**Comment by mafredri** [comment]
Hmm, I can't see the doubled site header, but it looks like pikabu.ru uses infinite scrolling. Most likely that has something to do with the footer looking incorrect.

E.g. maybe just as Chrome sets the page viewport, the site starts loading more content.

Not sure how to deal with that, maybe:
* Try to disable JavaScript, if possible
* Analyze page source and disable infinite scrolling (e.g. replace JS function)
* Use network interception before taking the screenshot and block network requests

Maybe this also classifies as a headless bug? Might be worth reporting to the headless mailing list and/or reporting on the chromium bug tracker.

**Comment by s3rj1k** [comment]
can you provide example on "Use network interception before taking the screenshot and block network requests" ?

**Comment by s3rj1k** [comment]
lol, with Google Chrome 66.0.3359.33 beta everything is superb
still would be nice to test with block network requests

**Comment by mafredri** [comment]
Heh 😅, updating Chrome often helps (esp. when using headless).

You can see some example uses of interception in #40, #36, #32. Although, some of those might be a bit outdated since Chrome changed the network interception API (I believe #40 at least is up-to-date).

But most likely you just need to begin interception, there's probably no need to "reply" (e.g. continue) to them.

**Comment by s3rj1k** [comment]
@mafredri  can I just use c.Page.StopLoading(ctx) instead of interception?

**Comment by mafredri** [comment]
I'm not an expert, but judging from the documentation I don't think it does anything to prevent future network requests.

**Comment by s3rj1k** [comment]
hmm, that could be true, still has to be enough for quick screenshot after stopping page load.

that for your support, closing this one. :+1:
