### ISSUE TITLE
How do I set Locale?

### ISSUE THREAD

**Issue by s3rj1k** [mafredri/cdp#53]
I would like to set custom locale? Is there any way to achieve this?

**Comment by mafredri** [comment]
The protocol exposes no way to do this at the moment, I think you'll have to set it via command line flag when launching headless Chrome (`--lang=en-US`).

Mind you, the flag seems to be ignored without headless, so you probably have to modify Chrome settings for that one.

**Comment by s3rj1k** [comment]
Hi, sorry for late replay

I was looking for example SetExtraHTTPHeaders with setting Accept-Language headers
https://developer.mozilla.org/ru/docs/Web/HTTP/%D0%97%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BA%D0%B8/Accept-Language

Can you provide simple example for that?

**Comment by mafredri** [comment]
Could you open a new issue instead? Repurposing old ones makes any potential solutions harder for others to find. If you could also answer what you tried / what issue you experienced, that would be helpful :).

PS. Was this issue (locale) resolved?

**Comment by s3rj1k** [comment]
@mafredri yes, sorry
