### ISSUE TITLE
Provide example for SetExtraHTTPHeaders

### ISSUE THREAD

**Issue by s3rj1k** [mafredri/cdp#54]
I was looking for example SetExtraHTTPHeaders for setting [Accept-Language](https://developer.mozilla.org/ru/docs/Web/HTTP/%D0%97%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BA%D0%B8/Accept-Language) headers

**Comment by mafredri** [comment]
I wasn't sure at first why you needed an example of this, but I took a look at the input arguments to the function and noticed what might be the reason.

Headers are defined as:

```go
// Headers Request / response headers as keys / values of JSON object.
type Headers []byte
```

It is kept as a byte slice (raw JSON) to make it more convenient to decode headers into any type of struct (instead of, say a `map[string]string`).

Maybe I could add a convenience method to create headers from a map as well, something like:

```go
func HeadersFromMap(m map[string]string) (Headers, error) {
	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	return b, nil
}
```

Thoughts?

**Comment by s3rj1k** [comment]
@mafredri would be nice, more readable that way.

only map needs to defined from outside of library

**Comment by mafredri** [comment]
> only map needs to defined from outside of library

How do you mean?

**Comment by s3rj1k** [comment]
var headers map[string]string
...
HeadersFromMap(header)
...

**Comment by mafredri** [comment]
> You can return empty []byte on error 

But this would not inform the user that encoding failed, and debugging why something isn't working (or headers missing) would be non-obvious.

**Comment by s3rj1k** [comment]
User expect that returned value is non empty, so if it is actually empty, this is error 

although detailed err message would be hidden

**Comment by mafredri** [comment]
> User expect that returned value is non empty, so if it is actually empty, this is error

Why would you say that is?

Let's say `FromMap` was fed an empty map? Surely nil is a valid return value then. Or let's say we invoke `FromKV(...args)`, where args is an empty slice, again nil would be a very valid return value. Especially considering that in some cases we want `Headers` to be `nil` (when relying on `omitempty`).

In my opinion, a function that returns no error can also never fail (except maybe panic). Or at least, that is the common expectation for users.

**Comment by s3rj1k** [comment]
If it is a helper function, user will use it for marshalling supplied headers, so nil output would be an error from users point of view.

In this case user should validate input, that it is not empty ...slice or map, if it is not and func returns zero-sized variable this will tell that error accrued.

I agree on usage case of panic, but panic often complicates things.

Can we just return data and error?

**Comment by mafredri** [comment]
> If it is a helper function, user will use it for marshalling supplied headers, so nil output would be an error from users point of view.

I don't trust that every user will see this the same way. Consider the following (given above implementation):

```go
var keyvals []string
if shouldAddHeadersY {
    keyvals = append(keyvals, "My-AwesomeY", "Header")
}
if shouldAddHeadersX {
    keyvals = append(keyvals, "My-AwesomeX", "Header")
}
headers := network.HeadersFromKV(keyvals...)
c.Network.SetExtraHTTPHeaders(headers)
```

I'm struggling to see any use case where `nil` from network.HeadersFromKV should be an error, and this totally feels like code I might write.

> I agree on usage case of panic, but panic often complicates things.

Absolutely, and this is why `cdp` barely has any panics. And I'm not keen on introducing any ;).

> Can we just return data and error?

That's probably best, yeah :)

**Comment by s3rj1k** [comment]
Any time frame on this? I am eager to test this out :)

**Comment by mafredri** [comment]
Sorry, can't provide any guarantees. I'll try to get around to it soon, probably during next week at the latest.

**Comment by mafredri** [comment]
Sorry, still haven’t gotten around to give this enough thought. I try to avoid making breaking changes which unfortunately also means I end up spending a lot of time thinking of solutions before pushing them out 😕.

**Comment by mafredri** [comment]
@s3rj1k I'm struggling with finding a good purpose for adding this to the library. Considering the `HeadersFromMap` from above, it really is no different than replacing `network.HeadersFromMap` with `json.Marshal` in the code. Both require error checking, so it's doesn't even increase convenience.

The only reason to add it, that I can think of, is to:

* Aid with discoverability / purpose of the `Headers` type.

But IMO this could be accomplished by improving the code comment for `type Headers`.

What are your thoughts @s3rj1k?

**Comment by s3rj1k** [comment]
Hi @mafredri, you can just provide detailed example on how to do it and no changes will be required for library.

**Comment by mafredri** [comment]
I'm not sure I understand what type of example you're asking for?

You could use it like this:

```go
err := c.Network.SetExtraHTTPHeaders(ctx,
	network.NewSetExtraHTTPHeadersArgs(
		[]byte(`{"Content-Type": "text/html; charset=utf-8"}`),
	),
)
```

But IMO this information is already available in this thread, is it something else you're looking for?

**Comment by s3rj1k** [comment]
@mafredri Hi, sorry for late reply

can't get working NewSetExtraHTTPHeadersArgs nor c.Emulation.SetUserAgentOverride
:(

**Comment by mafredri** [comment]
Can you post the code that you've tried to use? I'll try to have a look during this week.

**Comment by s3rj1k** [comment]
https://gist.github.com/s3rj1k/fa6d9b4da2a97666a6eb20d3e3fd077c

modified test case, output should include [HTTP_ACCEPT_LANGUAGE] header

**Comment by mafredri** [comment]
Have you tried enabling the Network domain? After adding `c.Network.Enable(ctx, nil)`, it works for me. Running Chrome Version 68.0.3440.59 (Official Build) beta.

**Comment by vjiandani-r7** [comment]
I'm having this same problem. I'm using Chrome Version 68.0.3440.106. I used your suggestion to eliminate any other possibilities. My code looks exactly like the following. I tested it with google.com and it creates the pdf without any issues but it doesn't work on a site that actually needs the header.

```
func CreatePdf(ctx context.Context, request GeneratePdfRequest) ([]byte, error) {

	//headers, marshallErr := json.Marshal(request.Headers)
	//if marshallErr != nil {
	//	return nil, marshallErr
	//}
	//extraHeaders := network.NewSetExtraHTTPHeadersArgs(headers)

	// Use the DevTools API to manage targets
	devt := devtool.New("http://127.0.0.1:9222")
	pt, _ := devt.Create(ctx)
	defer devt.Close(ctx, pt)

	// Open a new RPC connection to the Chrome Debugging Protocol target
	conn, _ := rpcc.DialContext(ctx, pt.WebSocketDebuggerURL)
	defer conn.Close()

	// Create new browser context
	baseBrowser := cdp.NewClient(conn)
	newContextTarget, _ := baseBrowser.Target.CreateBrowserContext(ctx)

	// Create a new blank target with the new browser context
	newTargetArgs := target.NewCreateTargetArgs("about:blank").
		SetBrowserContextID(newContextTarget.BrowserContextID)
	newTarget, _ := baseBrowser.Target.CreateTarget(ctx, newTargetArgs)

	// Connect the client to the new target
	newTargetWsURL := fmt.Sprintf("ws://127.0.0.1:9222/devtools/page/%s", newTarget.TargetID)
	newContextConn, _ := rpcc.DialContext(ctx, newTargetWsURL)
	defer newContextConn.Close()
	c := cdp.NewClient(newContextConn)

	// Close the target when done
	// (In development, skip this step to leave tabs open!)
	closeTargetArgs := target.NewCloseTargetArgs(newTarget.TargetID)
	defer baseBrowser.Target.CloseTarget(ctx, closeTargetArgs)

	// Enable the runtime
	err := c.Runtime.Enable(ctx)
	if err != nil {
		return nil, err;
	}

	// Enable the network
	_ = c.Network.Enable(ctx, network.NewEnableArgs())
	//_ = c.Network.SetExtraHTTPHeaders(ctx, extraHeaders)
	c.Network.SetExtraHTTPHeaders(ctx,
		network.NewSetExtraHTTPHeadersArgs(
			[]byte(`{"CDN_BUCKET": "//s3.amazonaws.com/com.rapid7.razor.cdn.test/ea-staging/1534559081974/"`),
		),
	)

	// Enable events on the Page domain
	_ = c.Page.Enable(ctx)

	// Create a client to listen for the load event to be fired
	loadEventFiredClient, _ := c.Page.LoadEventFired(ctx)
	defer loadEventFiredClient.Close()

	// Tell the page to navigate to the URL
	navArgs := page.NewNavigateArgs(request.TargetUrl)
	c.Page.Navigate(ctx, navArgs)

	// Wait for the page to finish loading
	_, _ = loadEventFiredClient.Recv()

	// Print to PDF
	printToPDFArgs := page.NewPrintToPDFArgs().
		SetLandscape(request.Orientation == "Landscape").
		SetPrintBackground(true).
		SetMarginTop(0).
		SetMarginBottom(0).
		SetMarginLeft(0).
		SetMarginRight(0).
		SetPrintBackground(true)
	pdf, _ := c.Page.PrintToPDF(ctx, printToPDFArgs)

	return pdf.Data, nil
}
```

**Comment by mafredri** [comment]
@vjiandani-r7 I really do recommend checking for errors, for example, the JSON you are using in `network.NewSetExtraHTTPHeadersArgs` is invalid. I believe `c.Network.SetExtraHTTPHeaders` should tell you this as well when checking the error.

Hope that fixes it!

**Comment by vjiandani-r7** [comment]
I added in error handling and confirmed that I fixed the error `Error: cdp.Network: SetExtraHTTPHeaders: json: error calling MarshalJSON for type network.Headers: unexpected end of JSON input`.

It still doesn't work.

**Comment by mafredri** [comment]
@vjiandani-r7 how did you confirm that it doesn't work? Have you looked at the headers sent to the webserver?

Here's [a gist](https://gist.github.com/mafredri/2f413e7bd1fe6e7d5afd2318f2a01549) of what I've used to test this and there are no issues setting / sending the headers.

**Comment by vjiandani-r7** [comment]
@mafredri Hmm I confirmed with your gist that the headers are being passed along correctly but I'm still having issues. I'll have to do some more debugging to figure out why the page I'm trying to load thinks they're missing. Thanks for your help.

**Comment by mafredri** [comment]
@vjiandani-r7 alright, I hope you figure it out!

@s3rj1k I hope this issue was resolved for you, feel free to re-open if there's anything left to discuss.
