### ISSUE TITLE
Get wss frame data

### ISSUE THREAD

**Issue by Poincare2013** [mafredri/cdp#58]
How can i get website's wss frame data by c.Network?Could you give me some example?Thanks!

**Comment by mafredri** [comment]
Have you tried using [Network](
https://godoc.org/github.com/mafredri/cdp#Network) event like `WebSocketFrameReceived`?

Remember to call `Network.Enable()` to enable events as well :). The [GoDoc examples](https://godoc.org/github.com/mafredri/cdp#pkg-examples) should help you get started.

**Comment by mafredri** [comment]
Closing due to age, let me know if this is still a problem.
