### ISSUE TITLE
Getting network requests or current page's URL

### ISSUE THREAD

**Issue by botherder** [mafredri/cdp#59]
I'm trying to use cdp to monitor network requests to follow a chain of redirects. Ideally I would manage to get all the visited URLs, but in the worst case I need the very last opened URL.
I understand the best way to do this with Chrome Devtools protocol is to monitor for Page.frameNavigated events and extract the frame URL. Quickly searching through the code it seems this event is not supported? What would be the best way to implement this using cdp?
Thanks for your work!

**Comment by mafredri** [comment]
I'm not sure how you searched through the code, but the event is definitely there 😄.

You can call `*(cdp.Client).Page.FrameNavigated(ctx)` to create an event client that listens for the event. And additionally, you'll need to call `*(cdp.Client).Page.Enable(ctx)` to enable the Page domain events.

I recommend checking the [GoDoc](https://godoc.org/github.com/mafredri/cdp) page to see search through the debugging protocol methods and events.

Let me know if you have any other issues!

**Comment by mafredri** [comment]
No problem 😄.

I think `Page.DOMContentEventFired` should suffice for your use case, as used in [Example](https://godoc.org/github.com/mafredri/cdp#example-package). But keep in mind that it does not guarantee that all JavaScript / remote network requests have completed executing.

PS. If you do use the `Ready()` channel, remember to also call `Recv()` if you will be re-using the event client as otherwise the `Read()` channel will stay closed/unblocking.

**Comment by botherder** [comment]
Thanks for the pointers. I suspect that Page.DOMContentEventFired will trigger when any first page is loaded, which I think you're right in that it should suffice for 302 redirects. I guess for JavaScript redirects that wouldn't. For the moment I am just waiting for 5 seconds before calling the DOMContentEventFired Recv(). I guess that should work for most cases.

**Comment by mafredri** [comment]
Yeah, I don't really have a good solution for JS redirects. Although, I would suggest waiting 5 seconds (or 6, assuming 5 is the standard redirect timeout) *after* `DOMContentEventFired`. I'd imagine that's when the JS timer starts. Via something like this:

```go
select {
case <-frameNavigated.Ready():
    frameNavigated.Recv()
    // retry wait for dom content event fired
case <-time.After(6*time.Second):
    // yay
}
```

(You could consider using either `FrameScheduledNavigation` or `FrameStartedLoading` instead of `FrameNavigated` here.)

> Thanks for your work. This library in Go made the whole process a lot less painful than what I was previously doing in Python.

Happy to hear 😄!

**Comment by botherder** [comment]
Thanks for the pointers.
Currently I'm doing like so:

```
	go func() {
		for true {
			select {
			case <-requestWillBeSent.Ready():
				event, err := requestWillBeSent.Recv()
				if err == nil {
					if event.Initiator.Type == "other" && *event.Type == page.ResourceTypeDocument {
						log.Debug("Network request to ", event.DocumentURL)
					}
				}
			case <-frameNavigated.Ready():
				event, err := frameNavigated.Recv()
				if err == nil {
					if event.Frame.ID == nav.FrameID {
						log.Debug("Browser has visited URL ", event.Frame.URL)
					}
				}
			}
		}
	}()

	_, err = domContent.Recv()
	if err != nil {
		log.Error(err)
	}
	time.Sleep(BrowserWaitTime * time.Second)
```

It is not very elegant. I'm placing it in a loop to be able to record all the `requestWillBeSent` events. Should I get rid of the `domContent.Recv()` and place the `time.After` as you suggested?

**Comment by mafredri** [comment]
Nah, the way you're doing it looks fine :).

**Comment by botherder** [comment]
Thanks for the help!

**Comment by wanhl1990** [comment]
Hi @botherder ,  @mafredri . I want get the response body from requestWillBeSent , but I can't find the api or elments.  There are only response status and headers,  but body is not exist.  Can I get it with cdp ?

**Comment by mafredri** [comment]
@wanhl1990 did you try [(Network).GetResponseBody](https://godoc.org/github.com/mafredri/cdp#Network)?

**Comment by wanhl1990** [comment]
> @wanhl1990 did you try [(Network).GetResponseBody](https://godoc.org/github.com/mafredri/cdp#Network)?

Yeah, I have try  GetResponseBody , but  get the response body after redirection also.   I use the dev tools on chrome (f12), use the Network label, can't get the body too.  Maybe the chrome do not support it?

**Comment by mafredri** [comment]
@wanhl1990 AFAICT you should be able to do fetch the body if you wait until the `ResponseReceived` event and then do: `GetResponseBody(ctx, network.NewGetResponseBodyArgs(ev.RequestID))`.

**Comment by wanhl1990** [comment]
> @wanhl1990 AFAICT you should be able to fetch the body if you wait until the `ResponseReceived` event and then do: `GetResponseBody(ctx, network.NewGetResponseBodyArgs(ev.RequestID))`.

Can't get also. :(   Maybe I can try another way to get . Like net/http  - -! Thank you mafredri.
