### ISSUE TITLE
How can I get HTTP response?

### ISSUE THREAD

**Issue by NzKSO** [mafredri/cdp#61]
Hello, I am working on my own project, one of feature uses your awesome library and I need to use it to get a HTTP response (include header), but I read the official devtools protocol documentation and your project documentation, it seems that there is no related API provided. Is there any way to do that?

**Comment by mafredri** [comment]
Hey, you should be able to do this via the `Network` domain. If all you care about are responses, you could listen to the `ResponseReceived` event and if you need the response body, you should be able to get it via:

```go
Network.GetResponseBody(ctx, network.NewGetResponseBodyArgs(ev.RequestID))
```

The headers should be available in `ev.Response.Headers`.
