### ISSUE TITLE
Recent change of RequestType causing issues

### ISSUE THREAD

**Issue by botherder** [mafredri/cdp#62]
I noticed that recently some references for network event types have been changed and moved around, but I can't quite figure out how to resolve this.

I noticed that `page.ResourceTypeDocument` was moved to `network.ResourceTypeDocument` and I fixed like this:

```go
event, err := requestWillBeSent.Recv()
if err == nil {
    if event.Initiator.Type == "other" && *event.Type == network.ResourceTypeDocument { ... }
```

Yet this error is still raised:

```
../browser.go:261:44: invalid indirect of event.Type (type "github.com/mafredri/cdp/protocol/network".ResourceType)
make: *** [Makefile:24: linux] Error 2
```

Although looking at the code, it seems that Type is still present in the `RequestWillBeSentReply`. Could you clarify? Thanks!

**Comment by botherder** [comment]
Nevermind, seems like just replacing *event.Type with event.Type did the trick.

**Comment by mafredri** [comment]
Sorry about that, I would love to provide a migration period for these kinds of things but at this time we’re at the mercy of the protocol definitions in Chrome. I’m glad you managed to solve the issue!

I’m planning a rewrite of `cdpgen` but even then it’s unlikely I’ll have time to add proper backwards compat for protocol changes 😔. But at least it should become easier to generate your own from any version of the protocol!
