### ISSUE TITLE
Incognito mode

### ISSUE THREAD

**Issue by ziflex** [mafredri/cdp#65]
Hi,

is there a way to open a new browser tab in incognito mode? If not, is there is a way to clear cache for that tab in order to use it as an incognito?
It seems ``pupeeter`` has some issues with incognito mode, so probably there is not functionality in place.

**Comment by mafredri** [comment]
Hey,

you can do this via the `Target` domain by creating a new browser context and creating new targets in that context (and the `session` package can be used to communicate with targets to avoid opening new websocket connections).

I thought this was worthy of an example: https://github.com/mafredri/cdp/commit/9c86381fa9c774b688f3c932f8718015015b93c2

**Comment by mafredri** [comment]
PS. I actually started working on a `browser` (or `browsertool`) package quite some time ago. It's purpose is managing tabs (targets), connections to them (sessions) and also creating / destroying incognito windows.

I couldn't settle on an API or specific parts of it's behavior, so eventually I split it off into a smaller, `session` package (that's how it was born). It's still on my back-burner and I try to return to it every now and a then. It would simplify this (and many other) use-cases tremendously.

Here's a look at what it looked like at one point:

```
type Browser struct {
	// Has unexported fields.
}
    Browser is a connection to a Chrome DevTools Protocol target representing
    the browser.


func (b *Browser) Attach(t *Target) (*rpcc.Conn, error)
func (b *Browser) Close() error
func (b *Browser) Focus(t *Target) error
func (b *Browser) NewContext() (*BrowserContext, error)
func (b *Browser) NewPage() (page *Target, conn *rpcc.Conn, err error)
func (b *Browser) Pages() []*Target
func (b *Browser) Shutdown(ctx context.Context) error
func (b *Browser) Targets() []*Target
func (b *Browser) Version() string

type BrowserContext struct {
	// Has unexported fields.
}
    BrowserContext represents a browser context, similar to an private/incognito
    window (headless Chrome only).


func (bc *BrowserContext) Close() error
func (bc *BrowserContext) NewPage() (page *Target, conn *rpcc.Conn, err error)
func (bc *BrowserContext) String() string
```

**Comment by ziflex** [comment]
This level of abstraction would be super useful!
In what state is this work now? Do you need some help?

**Comment by mafredri** [comment]
Talking with the incognito example as baseline, both the browser connection (`bconn`) and session manager are intended to be long-running. As such it's recommended to close a `conn` (from `sess.Dial`) when you're done with it. But closing the manager (`sess.Close()`) will also close all connections that were created by it.

https://godoc.org/github.com/mafredri/cdp/session#Manager.Close
