### ISSUE TITLE
Dispatch an event using NodeID/BackendID only

### ISSUE THREAD

**Issue by ziflex** [mafredri/cdp#66]
Hey,

is there a way to dispatch click (actually, any event) using only NodeID/BackendID?
I know that it's possible using JS eval, but in this case I have to use CSS selectors.
But for example, If I have an Node, is there a way to dispatch an event against it?
There are mouse events, which theoretically can trigger click event, but I need to get an element location which is challenge too.

**Comment by mafredri** [comment]
There's the `Runtime.CallFunctionOn` method (you could use it to call `[node].click()`, for example). But other than that, I don't know of any other method than what you already mentioned (e.g. figure out element location and perform a mouse click event on it's coordinates).

**Comment by ziflex** [comment]
@mafredri i'm a bit confused by the way how to call the function. Here is my code:

```go
func (el *HtmlElement) Click() (values.Boolean, error) {
	ctx, cancel := el.createCtx()

	defer cancel()

	obj, err := el.client.DOM.ResolveNode(
		ctx,
		dom.NewResolveNodeArgs().
			SetNodeID(el.id),
	)

	if err != nil {
		return values.False, err
	}

	if obj.Object.ObjectID == nil {
		return values.False, nil
	}

	res, err := el.client.Runtime.CallFunctionOn(
		ctx,
		runtime.NewCallFunctionOnArgs(fmt.Sprintf("window['%s'].click()", obj.Object.String())).
			SetObjectID(*obj.Object.ObjectID),
	)

	if err != nil {
		return values.False, err
	}

	if res.ExceptionDetails != nil {
		return values.False, res.ExceptionDetails
	}

	return values.True, nil
}
```

Obviously, it's not the right way of doing this. How variable should I use for requested remote objects?

**Comment by mafredri** [comment]
I haven't used this API myself, but I think the CallFunction args should be more like: `runtime.NewCallFunctionOnArgs("click").SetObjectID(*obj.Object.ObjectID)`.

**Comment by ziflex** [comment]
@mafredri unfortunately, I'm getting this error: ``ReferenceError: click is not defined``.

I've managed doing click using ``dispatchEvent`` method though.

```go
func (el *HtmlElement) Click() (values.Boolean, error) {
	ctx, cancel := el.createCtx()

	defer cancel()

	// get a ref to remote object representing the node
	obj, err := el.client.DOM.ResolveNode(
		ctx,
		dom.NewResolveNodeArgs().
			SetNodeID(el.id),
	)

	if err != nil {
		return values.False, err
	}

	if obj.Object.ObjectID == nil {
		return values.False, nil
	}

	evt, err := el.client.Runtime.Evaluate(ctx, runtime.NewEvaluateArgs(PrepareEval(`
		return new window.MouseEvent('click', { bubbles: true })
	`)))

	if err != nil {
		return values.False, nil
	}

	if evt.ExceptionDetails != nil {
		return values.False, evt.ExceptionDetails
	}

	fmt.Println(evt.Result.String())

	if evt.Result.ObjectID == nil {
		return values.False, nil
	}

	res, err := el.client.Runtime.CallFunctionOn(
		ctx,
		runtime.NewCallFunctionOnArgs("dispatchEvent").
			SetObjectID(*obj.Object.ObjectID).
			SetArguments([]runtime.CallArgument{
				{
					ObjectID: evt.Result.ObjectID,
				},
			}),
	)

	if err != nil {
		return values.False, err
	}

	if res.ExceptionDetails != nil {
		return values.False, res.ExceptionDetails
	}

	return values.True, nil
}
```

**Comment by mafredri** [comment]
Interesting approach, glad you found a solution, and thanks for sharing! I had imagined my example would work on a DOM element (e.g. a button) that has a click function, but perhaps it doesn't.

**Comment by ziflex** [comment]
@mafredri sure! By some reason, ``click`` didn't work, even though in Chrome itself it worked just fine. 
So I switched to the universal fallback solution with an event dispatch which works like a charm. :)

**Comment by ziflex** [comment]
Have to admit that the library is very stable. Didn't have any problems so far 👍

**Comment by mafredri** [comment]
@ziflex awesome, happy to hear! This library is very low-level but stability was one of my main goals and a big reason for creating it. I wanted to provide guarantees about the behavior and create reproducible outcomes 😄. I always wanted to create a higher level API on top of it, but never found the time, heh.

**Comment by bundleman** [comment]
@ziflex I ran into a situation when dispatchEvent  is forbidden (event.isTrusted == false) and it is approach does not work
