### ISSUE TITLE
Navigate after blank page

### ISSUE THREAD

**Issue by ziflex** [mafredri/cdp#67]
Hi,

it seems that if you create a tab with open blank page first and then try to navigate to another page - navigation does not happen, even though there are no errors.

**Comment by ziflex** [comment]
Ok, it seems it navigates, but ``Page.LoadEventFired`` does not get called at the right time.

**Comment by mafredri** [comment]
I don't think I understand the issue properly, could you clarify how the event comes in at the wrong time? Has the page domain been enabled and event client initialized before navigation?

**Comment by ziflex** [comment]
@mafredri I see there are some issues related to blank page in ``puppeteer`` too.
So, whenever you create a new blank page and then navigate to a web page, by some reason, LoadEventFired does not really handle page load and gets fired just before the target page gets loaded.

Hope, it makes sense :)

**Comment by mafredri** [comment]
I see. If it's a problem in puppeteer as well, I wonder if there's anything we can do about it. But at least we can try to analyze it. Could you either provide some code to reproduce the issue or provide some log output from the rpcc messages (e.g. via log example from godoc)?

**Comment by ziflex** [comment]
@mafredri sure, thanks!
