### ISSUE TITLE
rpcc: the connection is closing

### ISSUE THREAD

**Issue by ziflex** [mafredri/cdp#68]
Hi there,

Occasionally, I get this error when I load a document and try to get a root element:
```
cdp.DOM: GetDocument: rpcc: the connection is closing
```

any ideas why is it happening?

**Comment by mafredri** [comment]
Ah, the *best* kind of problem 😅. I think even logs would help debug the issue, if that's an option.

**Comment by ziflex** [comment]
@mafredri I'm currently fighting with node id issues. So, probably will get to this issue later.
It turned out, that not all methods you can invoke using ``Runtime.CallFunctionOn``. One of these methods are ``querySelector`` and ``querySelectorAll``.

**Comment by artooro** [comment]
I'm getting this error as well, but it's really strange because it doesn't happen on my macbook, but when I run my app on our linux server this error happens, on one specific web site. I haven't been able to narrow down why yet.

**Comment by mafredri** [comment]
Hmm, this got me thinking that there are situations where the error message is not propagated to the calling code in any meaningful way (only connection closing, gee thanks!).

Are you able to reproduce with #74 and get a more meaningful error?

My hunch is that what you're experiencing is the underlying websocket connection dying while there is no active calling code (e.g. no active stream and no active method being invoked). In that scenario, without #74, the actual error that killed the connection would not be propagated and all consecutive calls would simply see the `rpcc: the connection is closing` error.

**Comment by ziflex** [comment]
I did a refactoring in my lib and it seems the issue has gone. Probably I was doing something wrong :)
