### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by ziflex** [mafredri/cdp#72]
Hi,

I guess since you know much more about the library and Chrome DevTools Protocol itself , it's better to ask here:
How do you think whether your package (or protocol) can support a cluster of remote Chrome instances  without losing a context of an working tab?

**Comment by mafredri** [comment]
What type of clustering are you thinking of? Say; one rpcc connection that automatically balances requests between N chrome instances? If you could describe the setup in a bit more detail I'd have a clearer picture of how it could be done, but I think it should be possible without too much work.

**Comment by ziflex** [comment]
I was thinking about sticking one rpcc connection to a specific instance. 
I don’t have a specific set up at this moment.
I was just thinking about bunch of Chrome machines with load balancer / proxy in front of them.

**Comment by slotix** [comment]
Thank you, @mafredri for your CDP bindings! It is really cool and powerful.
I'm interested also to support Chrome Headless instances balancing with sticky sessions. 

How to send all requests during a specific user session to the same Chrome instance?

**Comment by mafredri** [comment]
@slotix thanks, glad you like it.

> How to send all requests during a specific user session to the same Chrome instance?

I'd say it depends on a lot of factors, it's a bit too big of a question for me to answer without knowing more of what you are already doing or have attempted. Does a chrome instance represent a tab, a window or multiple chrome processes? And how are you managing multiple chrome instances at the moment?

**Comment by slotix** [comment]
@mafredri, Thank you for your answer. We've discovered that DigitalOcean  has built-in sticky sessions support in their "load balancer" service.
We will try that and let you know about the results.
