### ISSUE TITLE
cdp.Runtime: Evaluate: context deadline exceeded

### ISSUE THREAD

**Issue by wanhl1990** [mafredri/cdp#73]
Hi ,  
I have a problem with Runtime.Evaluate function 
`cdp.Runtime: Evaluate: context deadline exceeded` .  Maybe my JS called a long time.  When it occurred ,  I can't do anything about context, e.g.  to c.page.Close(ctx) .  It may cause source leak? How can I to close the current target and something with it .

`ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
// devtool create, dial ,new client and so on. 

eval, err := c.Runtime.Evaluate(ctx, runtime.NewEvaluateArgs(script))
	if err != nil {
		logs.Error("Evaluate error ", err)
		return nil, err
	}
`

**Comment by mafredri** [comment]
Hey,

If you would like to call additional methods after a context has been cancelled / timed out, you will need to create a new context because all operations are basically no-op with a cancelled context. So ctx -> Eval -> Timeout -> newCtx -> page.Close(newCtx). Does that help / make sense?

**Comment by wanhl1990** [comment]
Oh， Thanks， Maybe this is a Low-level problem. :)
