### ISSUE TITLE
websocket: bad handshake

### ISSUE THREAD

**Issue by tarunrathor-pro** [mafredri/cdp#75]
Hi

I have a containerized version of the golang service using this library to communicate with chrome headless running on a separate container. Both these containers are deployed as services in kuberentes. On a local kubernetes environment running in minikube the golang service is failing to establish the connection with the chrome service. More specifically the devtool.Create call fails with 'websocket: bad handshake' error.

devt := devtool.New(chromeService)
pt, err := devt.Create(ctx)

The curious case is if i run this golang service on my host system (outside of kubernetes) it is able to connect and operate succefully with the chrome-headless running on minikube. 

Only when it is running inside minikube and trying to communicate with chrome then it fails.

Kindly advise

**Comment by mafredri** [comment]
Hi, it looks like you're hitting this code path: https://github.com/mafredri/cdp/blob/d811dcc98c8acf5bad67d2ce26eb3cb955a9013b/devtool/devtool.go#L92-L93

This was supposed to only be triggered on old headless versions of Chrome where the end-point wasn't implemented (thus returning 500). I realize it's a bit too general though, we can't assume that a 500 means that.

There's a chance that something else in front is returning error 500, triggering the code path, but the Chrome version is newer and doesn't have a hard coded path to the browser end-point (`/devtools/browser`).

Could you tell me what version of Chrome you're running in k8s? And you can try dumping the response before the above switch statement to see if it returns any more useful information.

**Comment by mafredri** [comment]
@tarunrathor-pro I've created #77, can you confirm if it fixes your issue? If it does, you should no longer see the bad handshake message and instead see an entirely different one.

**Comment by r3vit** [comment]
@mafredri Hi,

I got the same problem today. Yes, the issue is fixed (if the issue is "the error is generic")
I applied your fix and now the error returned is: 
```
time="2018-11-07T11:26:37Z" level=warning msg="Unable to crawl 'http://www.google.it' with chrome headless: devtool: 
  Version: Host header is specified and is not an IP address or localhost.: devtool: 
  CreateUrl: StatusInternalServerError: 
  Host header is specified and is not an IP address or localhost."
```

The issue is raised by the use of a hostname instead of an IP.
Docker manages my services and when one of them will go down, it will restart but the IP is assigned by Docker.
Unfortunately, I cannot use static IPs :(

Anyway, I really admire your work! It's a beautiful package! Thank you :)

**Comment by mafredri** [comment]
Thanks for the report @r3vit! I think we can solve this by always doing

**Comment by mafredri** [comment]
Ah, although, depending on if you have something in front or not, an IP might not be directed towards the correct container. Thoughts?

**Comment by r3vit** [comment]
In my setup there is nothing in front.

Ok, now it works without problems, with something similar to:
```go
	// Connect to DevTools.
	devToolURL = "headless" // Name of the container.
	// DNS lookup.
	devToolIPs, err := net.LookupIP(devToolURL)
	if err != nil {
		fmt.Printf("NET ERROR: %v\n", err)
	}
	// Range over ips and get the last one. (It may fail in some setup)
	for _, ip := range devToolIPs {
		devToolURL = ip.String()
	}
	// New devtool.
	devt = devtool.New("http://" + devToolURL + ":9222")
```
Thank you for the support! :)

**Comment by mafredri** [comment]
@r3vit you're welcome! Happy you got it working 😄.

I created a PR which should fix this issue https://github.com/mafredri/cdp/pull/78, if you have time to try it out that would be great!

I'm curious, why did you decide to pick the last IP from the lookup? In https://github.com/mafredri/cdp/pull/78 I decided to test all addresses we get back, and settle for the first one that works.

**Comment by r3vit** [comment]
> I'm curious, why did you decide to pick the last IP from the lookup? In #78 I decided to test all addresses we get back, and settle for the first one that works but I'd like to know if there was a specific reason for choosing the last one.

You did the right thing :) There are no particular reason for my last element choice.

Tested #78 locally and It works flawless for:
```
devToolURL := "http://headless:9222" // Name of the container with scheme and port.
```
I think this is the ideal solution. Caller can use the right scheme and port of his setup.

**Comment by mafredri** [comment]
Great, the branches are now merged in to master. Thanks for testing @r3vit!
