### ISSUE TITLE
Print to PDF: issues with header and footer templates

### ISSUE THREAD

**Issue by gulien** [mafredri/cdp#79]
Hello @mafredri ,

Thank you for the library, great job!

I'm currently trying to add a header and a footer when printing a page to PDF, but I've encountered some weird issues.

```golang
print, err := c.Page.PrintToPDF(
	html.Context,
	page.NewPrintToPDFArgs().
		SetLandscape(false).
		SetPrintBackground(true).
		SetMarginTop(0).
		SetMarginBottom(0).
		SetMarginLeft(0).
		SetMarginRight(0).
		SetDisplayHeaderFooter(true).
		SetHeaderTemplate(headerString).
		SetFooterTemplate(footerString).
		SetPaperWidth(8.27).
		SetPaperHeight(11.7),
	)
```

## Issues

1. When both header and footer templates are set, none of them appear in the resulting PDF
2. When only the header template is set, it is displayed at the bottom (like a... footer?) using what looks like a default template (date + title)
3. When only the footer template is set, it is displayed at the top (like a... header) using again what looks like a default template (URL + current page / total pages)

## Additional information

The page is actually a local file, nothing special about it. The margins are specified in CSS:

```css
@page { 
    margin: 25mm 25mm; 
}
```

Header template:

```html
<div style="background-color: green;">
 <span class="pageNumber"> of <span class="totalPages"></span>
</div>
```

Footer template:
```html
<div style="background-color: red;">
 <span class='pageNumber"> of <span class="totalPages"></span>
</div>
```

## System information

**Golang version:** 1.11.2
**Library version:** 0.20.0
**Chrome version:** 70.0.3538.110

**Comment by gulien** [comment]
@charleswklau I've just tested, it changes nothing unfortunately.

**Comment by mafredri** [comment]
Hey @gulien, glad you're liking cdp :)!

Regarding your issue, it does sound like there's not enough space for the header/footer to be rendered. Like @charleswklau suggested, you probably need to set a margin. In my experience, the margin needs to allocate enough space for the header / footer to fit in that space. There's no magics going on to make it fit into the document on the Chrome side.

I also believe that defining `@page` in CSS is insufficient unless you enable `PreferCSSPageSize`. There was some discussion about this in #37.

When I've used PDF printing in the past, I've opted to define the margins manually, and I've also provided a full HTML template for the header / footer.

```go
var headerFooterTmpl = template.Must(template.New("headerfooter").Parse(`
	<html>
	<head>
		<style>
			body {
				color: #444;
				font-size: 8rem;
				text-align: center;
			}
			.content {
				margin: 4rem auto;
			}
		</style>
	</head>
	<body>
		<div class="content">{{.Body}}</div>
	</body>
	</html>
`))
```

And args:


```go
pdfArgs := page.NewPrintToPDFArgs().
	SetPaperHeight(float64(1872) / 226).
	SetPaperWidth(float64(1404) / 226).
	SetMarginTop(0.65).
	SetMarginBottom(0.65).
	SetMarginLeft(0.65).
	SetMarginRight(0.65).
	SetHeaderTemplate(header).
	SetFooterTemplate(footer).
	SetDisplayHeaderFooter(true).
	SetPrintBackground(true).
	SetScale(1.25)
```

You could try to set overly large margins to see if the header and footer fit then.

**Comment by gulien** [comment]
Hey @mafredri!

So I just tried the following:

```golang
page.NewPrintToPDFArgs().
	SetLandscape(false).
	SetPrintBackground(true).
        SetPaperWidth(8.27).
	SetPaperHeight(11.7).
	SetMarginTop(3).
	SetMarginBottom(3).
	SetMarginLeft(3).
	SetMarginRight(3).
	SetDisplayHeaderFooter(true).
	SetHeaderTemplate(header).
	SetFooterTemplate(footer)
```


I've also removed `@page` instructions from my CSS and wrapped my footer and header inside `<html><body>` tags.

And... tada! I still got the same issues.

🤔 I'm wondering if:

1. the error is in my code
2. there is a comptability issue between my Chrome version and your library
3. ?

**Comment by gulien** [comment]
Ok, so after adding a `head` tag, it works! 🎉 

In other words, this works:

```html
<html>
 <head></head>
 <body>FOO</body>
</html>
```

But this doesn't:

```html
<html>
 <body>FOO</body>
</html>
```

Good to know though:

- CSS properties are shared between header and footer
- if a footer is set but no header, the default header is displayed
- if a header is set but no footer, the default footer is displayed

Thank you all for your time! 😄 

PS: I'm currently working on the third version of [Gotenberg](https://github.com/thecodingmachine/gotenberg), and your library really helps me to find a solid alternative to wkmhtmltopdf!

**Comment by mafredri** [comment]
@gulien oh wow, thanks for reporting back, that's an easy one to trip up on! We should probably report this to chromium as it might be a bug, or at best the protocol documentation should be updated.

Appreciate the good to knows 👍, might come in handy.

Very cool project you're working on, and I'm stoked you're finding cdp useful! Btw, is `epub` support on the agenda? Asking because I've been working on a `epub2pdf` converter that uses headless chrome for rendering as well 😄.

**Comment by gulien** [comment]
Hey, why not! I'm not familiar with epub, but the more the better 😄

**Comment by gulien** [comment]
Just a quick follow up: I've just released [Gotenberg v3](https://github.com/thecodingmachine/gotenberg).

I'll try to take a look at epub support, it seems to be a nice feature to add!

This issue is OK for me, feel free to close it 😄 thanks again!

**Comment by mafredri** [comment]
Nice!

I was thinking of keeping this issue open as a reminder to report this upstream, but I think I'll go ahead and close it anyway 😄.
