### ISSUE TITLE
cdp.Target: CreateBrowserContext: rpc error: Not allowed. (code = -32000)

### ISSUE THREAD

**Issue by gulien** [mafredri/cdp#80]
Hello again,

The following error is thrown in Travis CI and has also been reported here https://github.com/thecodingmachine/gotenberg/issues/15:

```
cdp.Target: CreateBrowserContext: rpc error: Not allowed. (code = -32000)
```

It happens here in my code: https://github.com/thecodingmachine/gotenberg/blob/master/internal/pkg/printer/html.go#L55

Google Chrome is installed in a Debian/stretch Docker image: https://github.com/thecodingmachine/gotenberg/blob/master/build/base/Dockerfile#L33.

And it is launched with PM2 using those options:

```
"--no-sandbox",
"--headless",
"--remote-debugging-port=9222",
"--disable-gpu",
"--disable-translate",
"--disable-extensions",
"--disable-background-networking",
"--safebrowsing-disable-auto-update",
"--disable-sync",
"--disable-default-apps",
"--hide-scrollbars",
"--metrics-recording-only",
"--mute-audio",
"--no-first-run",
```

🤔 I have now idea why it is happening. I cannot reproduce it locally (macOS with Docker) as those commands works as expected:

```bash
$ docker run --rm -p 3000:3000 thecodingmachine/gotenberg:3
$ curl --request POST \
    --url http://localhost:3000/convert/html \
    --header 'Content-Type: multipart/form-data' \
    --form files=@index.html \
    > result.pdf
```

Thank you! 😄

**Comment by mafredri** [comment]
I suspect this might be a Chrome version issue. In fact, I'm a bit surprised it works for you locally. At least historically, a browser context could not be created from a `Page`-endpoint. Instead, you had to connect to the `Browser`-endpoint (available via `/json/version`).

There's an example of using the browser endpoint in the incognito example, basically you'd change [thecodingmachine/gotenberg/internal/pkg/printer/html.go#L41-L52](https://github.com/thecodingmachine/gotenberg/blob/6ee1932cbfe7a46b3c6691671bbc8f3f7291c371/internal/pkg/printer/html.go#L41-L52) with:

https://github.com/mafredri/cdp/blob/1dba954bc11d39bb5404af37f3cf47e37171425d/example_incognito_test.go#L23-L35

Does making this change fix the issue?

**Comment by gulien** [comment]
Travis CI is now working as expected :tada: thank you for the quick answer!

**Comment by mafredri** [comment]
Glad to hear, no problem 😄!
