### ISSUE TITLE
Close target

### ISSUE THREAD

**Issue by ikonst** [mafredri/cdp#81]
This is probably not a question specific to mafredri/cdp.

When implementing a service on top of Chrome Headless, is it correct architecture-wise to share a Chrome process, given that Chrome itself successfully multiplexes subprocesses?

Does Chrome associate resources with a connected client? In other words, when I disconnect (especially abnormally), does Chrome keep resources (e.g. targets) alive expecting that my client will reconnect and re-claim them, or are they collected? If not, is there any good pattern to collect them?

**Comment by ikonst** [comment]
It's either tracking browser contexts or targets, but I'd have to track something.

I now realize that the preferable model is a 1:1 between Go service and Chrome instance (otherwise if the Go service crashes it cannot reliably know, upon restart, which browser contexts/targets belonged to it).

Then:
- upon connecting to a Chrome instance, close all existing targets (if any)
- if implementing a web service, use a background context rather than the request context when managing the targets, otherwise a disconnecting client would cancel the context and you'd fail to close the target

**Comment by mafredri** [comment]
I think that's a perfectly fine strategy. Alternatively you could design a Go service to act as a layer between the other service and Chrome, and that layer would then take care of destroying targets / contexts upon client disconnect.

> if implementing a web service, use a background context rather than the request context when managing the targets, otherwise a disconnecting client would cancel the context and you'd fail to close the target

This is a good observation you have made, and indeed one of the things I'd consider a small pain-point with the current implementation. It might feel natural to write something like `defer c.Target.CloseTarget(ctx, args)` but it would be a hidden bug if e.g. using a request context as you've observed. Ideally you would use two contexts, one for commands that you want to abort (request based) and another for terminating (perhaps with a timeout).

Another possibility is to cook up some form of practice of identifying targets, e.g. planting an identifier on the window-object (or local storage, cookie, etc) of the target or something along those lines. Not a perfect solution but could work in a pinch. Upon reconnect you could iterate through all targets and check the identifier.
