### ISSUE TITLE
RPC & WSS/TLS 

### ISSUE THREAD

**Issue by aaronn** [mafredri/cdp#82]
-

**Comment by mafredri** [comment]
Hi,

that's a good question actually. Normally the underlying websocket library (gorilla/websocket) handles wss connections if you pass a wss:// URL to Dial, however, if you need a custom TLS config it is not trivial.

The other option is to use the WithDialer(netDial) dial option, but this forces you to establish the websocket connection yourself and (unless it already is) wrap it as a io.ReadWriteCloser. The downside then is that you lose the writeLimiter which ensures a proper error is returned if you're sending a payload that's too big (Chrome doesn't support message fragmentation) and connections might just die abruptly.

It may be a good idea to document that the Dial function also accepts wss:// and perhaps expose a new dial option (WithTLSConfig) in rpcc.

**Comment by aaronn** [comment]
Yeah, I was looking for a way to do this with a custom TLS config (my clients all have certificates too). Exposing a new dial option would be great.

**Comment by mafredri** [comment]
@aaronn just pushed v0.21.0 (with 3083b7c), should allow you to do just that 😄!

**Comment by aaronn** [comment]
@mafredri amazing, thank you!
