### ISSUE TITLE
cdp.Target: CreateTarget: context deadline exceeded

### ISSUE THREAD

**Issue by charleswklau** [mafredri/cdp#83]
Hi, I have a problem when using CreateTarget.

```go
ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
bver, err := devtool.New("http://127.0.0.1:9222").Version(ctx)
conn, err := rpcc.DialContext(ctx, bver.WebSocketDebuggerURL)
browser := cdp.NewClient(conn)
ctxTarget, err := browser.Target.CreateBrowserContext(ctx)
tarArgs := target.NewCreateTargetArgs("about:blank").SetBrowserContextID(ctxTarget.BrowserContextID)
newTarget, err := baseBrowser.Target.CreateTarget(ctx, tarArgs)
```
....

I got fail when calling CreateTarget. But this error comes occasionally. I though it may be related to the version difference of chrome. But it seems not.
My main purpose is using chrome headless to generate PDF file, is the flow correct?

**Comment by mafredri** [comment]
The context you created on the first line has a timeout of 5 seconds, the reason you're seeing `context deadline exceeded` is that the time limit was hit. It should work if you increase the time limit.

**Comment by charleswklau** [comment]
what duration u will be suggested? It is because I think 5 seconds to long enough to take the conversion.

**Comment by charleswklau** [comment]
Thanks for your comments.
