### ISSUE TITLE
How I can open page with current cookies?

### ISSUE THREAD

**Issue by x777** [mafredri/cdp#85]
**Hi, thanks for your library. It's cool alternative for gophers instead Puppeteer Node.js.**

I am connecting to running instanse of chrome. I can get all cookies. But how open url with them?
Also, may you have some article with basic stuff "How to..click, parse, etc" for easiest way to start? Thx!

**Comment by mafredri** [comment]
You can take a look at the project examples, at least the `advanced` example uses cookies, maybe you can find some clues there.

For info on mouse click events you could look at: #35, #38, #66.

Unfortunately I don't know any articles that walk through all the aspects of the protocol, for a large part it's trial by fire 😅. You can check the readme for some good sources to scavenge some info.

**Comment by x777** [comment]
Trial by fire it's cool analogy 😅 Thanks

**Comment by mafredri** [comment]
Heh, no problem. Sorry I couldn't be of more help. But if you are stuck on something or wondering how something works, feel free to ask, happy to help.
