### ISSUE TITLE
Is it ready for production?

### ISSUE THREAD

**Issue by GildedHonour** [mafredri/cdp#87]
Is it ready for production?

**Comment by mafredri** [comment]
@GildedHonour sure, I don't see why not. We've been running it in production at my company for ~ 1,5 years and I believe some other have as well. Feel free to open new issues if you run into any problems with it.

**Comment by GildedHonour** [comment]
Okay.

Does it support Chrome DevTools Protocol completely?

Does it have any advantages over https://github.com/chromedp/chromedp ?

**Comment by mafredri** [comment]
> Does it support Chrome DevTools Protocol completely?

Yes, the `protocol` package is generated from the protocol definitions in chromium.

> Does it have any advantages over https://github.com/chromedp/chromedp ?

Fewer open issues 😅? Jokes aside, I don't think these projects are fully comparable. To me it seems like chromedp is higher level, focusing on browser automation. Whereas cdp focuses on exposing the full Chrome DevTools Protocol. In this project a lot of effort has gone into ensuring reliable usage of the protocol and being able to produce repeatable outcomes. Also, where possible, tries to do things in an idiomatic (Go) way. The [Feature](https://github.com/mafredri/cdp#features)-section in the readme lists some of these things. But honestly, how this all compares to chromedp I'm not sure.

Hope that helps.

**Comment by GildedHonour** [comment]
thx
