### ISSUE TITLE
Network.SetCookies causes Chrome crash

### ISSUE THREAD

**Issue by ziflex** [mafredri/cdp#88]
Hi there,

In context of [this issue](https://github.com/MontFerret/ferret/issues/236), I'm trying to provide a functionality to set cookies before page load.

Unfortunately, whenever I try to set cookies, Chrome crashes with ```Segmentation fault: 11``` error code.

Here is my code:

```go
func() error {
    if err := client.Network.Enable(ctx, network.NewEnableArgs()); err != nil {
        return err
    }

    if params.Cookies != nil {
        cookies := make([]network.CookieParam, 0, len(params.Cookies))

        for _, c := range params.Cookies {
            cookies = append(cookies, fromDriverCookie(c))

            logger.
                Debug().
                Timestamp().
                Str("cookie", c.Name).
                Msg("set cookie")
        }

        err := client.Network.SetCookies(
            ctx,
            network.NewSetCookiesArgs(cookies),
        )

        if err != nil {
            return err
        }
    }

    return nil
}
```

**Comment by mafredri** [comment]
@ziflex interesting issue. Chrome is sometimes very picky about it's input and doesn't handle unexpected input very well.

Could you show me what data is sent to Chrome? It could be one of the values set on one or all of the cookies. Also, does the singular `c.Network.SetCookie()` work better?

**Comment by mafredri** [comment]
I tried a few inputs and it looks like Chrome crashes if you don't set the `network.CookieParam.URL`. It's not even sufficient to set it to any value, it must be a valid URL with `http://` or `https://` even :/.

**Comment by ziflex** [comment]
> I tried a few inputs and it looks like Chrome crashes if you don't set the `network.CookieParam.URL`. It's not even sufficient to set it to any value, it must be a valid URL with `http://` or `https://` even :/.

It helped! Thanks!

**Comment by ziflex** [comment]
Ok, I have to reopen it since the issue occurs in Dockerized Chrome.

Any thoughts what else can be missing?

**Comment by mafredri** [comment]
What request (i.e. the RPC message) is crashing Chrome?

**Comment by mafredri** [comment]
@ziflex any update on this, is it still an issue?

**Comment by ziflex** [comment]
Hey, I'm sorry, forgot to close the issue!
Yes, it works fine, I just messed up with urls - Chrome doesn't like urls without ```http(s)://``` even if you want to open a web page.

**Comment by mafredri** [comment]
No worries, thanks for reporting back 😄!
