### ISSUE TITLE
is running and connecting to multi chrome instance(on different port) at the same time  possible?

### ISSUE THREAD

**Issue by kaixinbuyu** [mafredri/cdp#89]
eg,on the same golang process:
cdp1<-->exec.run chrome1[@localhost:9222]
cdp2<-->exec.run chrome2[@localhost:9223]

I tried and failed to do this.
cdp can not get connection if there are another exist chrome instance.

**Comment by mafredri** [comment]
There shouldn't be any issue in controlling multiple browsers to my knowledge. Could you provide me with some samples of what you tried to do and flags you used to start Chrome?

**Comment by kaixinbuyu** [comment]
1.In my case I want to run multi-user's chrome url requests.
**requests between users should be separated even it is the same url as they have different password and web content**. eg:
user1 use uname1,passwd1 login to www.ajax-page.com and take snapshot ,save png to user1's store;
user2 use uname2,passwd2 login to www.ajax-page.com and take snapshot ,save png to user2's store;

2.what I have tested is:
for separate cookie env,I have to lunch different chrome instance for each user.
create a map[user-id]*cdp-connect to->different chrome instance at different port. eg:
user1 use uname1,passwd1 login to www.ajax-page.com running on cdp1-conn-to-chrome[:9222]
user2 use uname2,passwd2 login to www.ajax-page.com running on cdp2-conn-to-chrome[:9223]

3.the question is that I found only one chrome can be lunched. othe chromes(9223,9224) are failed:

4.So what's the right way to do this?

**Comment by mafredri** [comment]
You could start two Chromes in your terminal, for example:

```shell
chrome --headless --remote-debugging-port=9222 --disable-gpu &
chrome --headless --remote-debugging-port=9223 --disable-gpu &
```

And then use cdp to connect to them like you normally would at `localhost:9222` and `localhost:9223`.

**Comment by kaixinbuyu** [comment]
thank you for your replying and I'll retry at once.
