### ISSUE TITLE
Are cdptype, cdpcmd, cdpevent meant to be public interfaces?

### ISSUE THREAD

**Issue by matthewmueller** [mafredri/cdp#9]
Hey @mafredri, I'm really digging this implementation. I've also noticed you on a couple common issues across github related to headless chrome – awesome stuff :-)

For my use case, I'm just using the generated types in this library, so I was wondering if those are meant to be public interfaces, or if you anticipate changing that up in the future?

Thanks!

**Comment by mafredri** [comment]
Thanks for the kind words @matthewmueller, I'm glad you're liking it!

> For my use case, I'm just using the generated types in this library, so I was wondering if those are meant to be public interfaces, or if you anticipate changing that up in the future?

Yes, they are indeed meant to be public! Although, there is a caveat. I'm currently considering the possibility of moving from separation by type/action (`cdp{cmd,event,type}`) to separation by domain name (`network`, `dom`, etc).

I did quite a bit of prototyping for the API in the beginning before ending up with the current structure. My original motivations were (among others):

* Avoid circular dependencies between the Chrome Debugging Protocol domains (e.g. `Network` references types from `Page` and vice-versa)
* Fewer imports (one import for commands, one for events, etc)
* Ease of use, user knows that commands are always in `cdpcmd`
* Prefix imports with `cdp` to avoid common collisions (`cmd`, `event`, `types`)

My current motivations for moving towards the domain-split:

* Maps more closely to the protocol specification and thus implementations in other languages
* All domain related types / commands / events are located in one single package
* Slightly shorter and easier to type `cdpcmd.NewRuntimeEvaluateArgs("")` -> `runtime.NewEvaluateArgs("")`
* Number of imports is limited by the number of domains used (usually ~3-4 for me)
* I find that e.g. `cdpcmd` stutters a bit and is occasionally hard to type correctly 😅
* With Go 1.9 type aliases we can easily, with minimal effort, eliminate circular dependencies

For the circular dependencies, we can get away with only moving `page.FrameID` and `page.ResourceType` to `internal.FrameID` and `internal.ResourceType` and set up type aliases for them in the `dom`, `network` and `page` domains. The user would be encouraged to keep using `page.FrameID` although either of `dom.FrameID` and `network.FrameID` would also work.

I would be happy to know how such a change might impact you, and what your thoughts are about it. Migrating existing code to the new structure should be fairly trivial, given some motivation this could even be automated 🙂.

**PS.** It's good that you brought this up now, I've been meaning to open up an issue about this and write down my thoughts, albeit *after* I was done with the branch that implements the new structure.

**Comment by matthewmueller** [comment]
awesome, thanks for the info! I'll be following along closely with this repo, so changes won't be a huge deal. I just wanted to make sure I wasn't going off on an unbeaten path :-)

**Comment by mafredri** [comment]
@matthewmueller I'm still not done, but if you're interested in seeing the effect of the API change that I'm working on,
 you can take a look at the [separate-domains](https://github.com/mafredri/cdp/tree/separate-domains)-branch. Specifically https://github.com/mafredri/cdp/commit/0428692d8726b0ef4fa08a9f970a677aa2fb03a1 will show you what changed (the examples are a good reference).

Honestly it's not a big change in how you use the library, but a pretty massive change to the generated code 😅.

(Note: does not use aliases yet, I'm thinking of including those behind a build flag for Go 1.9 to maintain Go 1.8 compatibility, right now the `DOM` and `Network` domains reference `string` instead of `Page.FrameID` and `Page.ResourceType` to quickly work around the circular dependency issue, but this will be improved upon later, at least for Go 1.9 via aliases).

**Comment by matthewmueller** [comment]
I took a look at the commit and it looks like a great API improvement. Thanks for the hard work here 😄 

I'm actually in the process of refactoring my code to use CDP's API from the top (devtool, client, rpcc, etc.) and not just the types, so there's a good chance I'll be able to help out with some of this work going forward.

**Comment by mafredri** [comment]
Thanks for taking a look, I'm glad you like the change 🙂. I'll try to get the branch wrapped up and merged soon.

> I'm actually in the process of refactoring my code to use CDP's API from the top (devtool, client, rpcc, etc.) and not just the types, so there's a good chance I'll be able to help out with some of this work going forward.

That's awesome! Looking forward to your input 😄!
