### ISSUE TITLE
Import emulated devices

### ISSUE THREAD

**Issue by derekperkins** [mafredri/cdp#93]
I see `SetDeviceMetricsOverride` in the api that I believe provides the low-level support necessary. Would it be possible to import the devices themselves with all their settings? 

http://chromedriver.chromium.org/mobile-emulation

![image](https://user-images.githubusercontent.com/3588778/56484029-bd8e6100-648a-11e9-91f0-c0b01a15596c.png)

**Comment by mafredri** [comment]
While there's no direct way to import those profiles as they are a part of Chrome DevTools (the UI), you could import them from [emulated_devices/module.json](https://github.com/paulirish/devtools-frontend/blob/bcd58bb81205d9ef67b942748c9366105d08d5ca/front_end/emulated_devices/module.json).

You can look at [emulation/DeviceModeModel.js#L564-L596](https://github.com/paulirish/devtools-frontend/blob/bcd58bb81205d9ef67b942748c9366105d08d5ca/front_end/emulation/DeviceModeModel.js#L564-L596) for how it's used in the front-end, and at [emulation/EmulatedDevices.js](https://github.com/paulirish/devtools-frontend/blob/bcd58bb81205d9ef67b942748c9366105d08d5ca/front_end/emulation/EmulatedDevices.js) for how the JSON is parsed.

**Comment by Pindar777** [comment]
@derekperkins 
Hi, 
did it work?
Is the import simply switching the emulated_devices/module.json file with a version containing the desired devices?
