### ISSUE TITLE
Create target in background

### ISSUE THREAD

**Issue by AlaNDGT** [mafredri/cdp#95]
Hi,

The latest browser protocol seems to provide an option to [create new target in the background](https://chromedevtools.github.io/devtools-protocol/tot/Target#method-createTarget).

Is that going to be updated in your package soon? Could you provide an estimated date when that could be done if the case?

Awesome library btw!

**Comment by mafredri** [comment]
Hi @AlaNDGT,

this project is currently using the JSON from the [ChromeDevTools/devtools-protocol](https://github.com/ChromeDevTools/devtools-protocol)-repo. As such, it's dependent on the repos rate of release, which is currently on r666501. It seems to me like it uses the chromium master branch to fetch the latest specification (in `pdl` format), but I don't know when it will land there.

For now, you could work around this by issuing the request directly via `rpcc`, something along these lines:

```go
reply := new(target.CreateTargetReply)
args := map[string]interface{}{
    "url": "http://my.url",
    "background": true,
}
err := rpcc.Invoke(ctx, "Target.createTarget", args, reply, conn)
```

I've been planning to implement the PDL parser in `cmd/cdpgen` but haven't gotten around to it yet. That would make us independent of the devtools-protocol repo and perhaps provide some extra type information lost in the JSON translation.

Another change I'm hoping to get around to is moving some type definitions from `cdp` to `protocol` (like Client, and the domains) whilst keeping type aliases around for backwards compatibility. That change, combined with go modules, would make it easy to generate your own `protocol` package from a JSON definition and simply override the `cdp/protocol` package with the newly generated one in the go module definition. Those are also part of a pending `cmd/cdpgen` refactor.

PS. I'm glad you're enjoying the library, hope this helps you work around the issue for now!

**Comment by AlaNDGT** [comment]
Oh, alright alright, can definitely do with that for the time being.

Had a look and seems that release r666501 does have the new option `background`. Would you be updating your repo in the near future in this case?

Thanks for your prompt reply!

**Comment by mafredri** [comment]
Oh, sorry about that. I took a quick look yesterday and couldn't spot the addition of `background`. Good eye.

I just pushed the update (`v0.23.3`).

**Comment by AlaNDGT** [comment]
Ah, you're awesome! Thanks
