### ISSUE TITLE
How do I download files？

### ISSUE THREAD

**Issue by LuciferoO** [mafredri/cdp#97]
Here is my code，I want to visit a site and download files。

The reponse header I use my pc to visit was.
```
HTTP/1.1 200 OK
Date: Tue, 18 Jun 2019 03:42:19 GMT
Content-Type: application/octet-stream
Content-Length: 146789
Connection: keep-alive
Content-disposition: attachment; filename=2017-03-13_2017-03-19.xml
X-Via-JSL: 6c1501f,-
X-Cache: bypass
```
I always got the error `[Error] cdp.Page: DOMContentEventFired Recv: context deadline exceeded`

Plz tell

```go
func RunChrome(url string, method string, data string, timeout time.Duration, chrome string) (string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()

	// Use the DevTools HTTP/JSON API to manage targets (e.g. pages, webworkers).
	devt := devtool.New(chrome)
	pt, err := devt.Get(ctx, devtool.Page)
	if err != nil {
		pt, err = devt.Create(ctx)
		if err != nil {
			return "", err
		}
	}

	// Initiate a new RPC connection to the Chrome Debugging Protocol target.
	conn, err := rpcc.DialContext(ctx, pt.WebSocketDebuggerURL)
	if err != nil {
		return "", err
	}
	defer conn.Close() // Leaving connections open will leak memory.

	c := cdp.NewClient(conn)

	downloadBehavior := page.NewSetDownloadBehaviorArgs("allow")
	downloadBehavior.SetDownloadPath("./download/")
	c.Page.SetDownloadBehavior(ctx, downloadBehavior)
	// Open a DOMContentEventFired client to buffer this event.
	domContent, err := c.Page.DOMContentEventFired(ctx)
	if err != nil {
		return "", err
	}
	defer domContent.Close()

	// Enable events on the Page domain, it's often preferrable to create
	// event clients before enabling events so that we don't miss any.
	if err = c.Page.Enable(ctx); err != nil {
		return "", err
	}

	if err = c.Network.Enable(ctx, nil); err != nil {
		return "", err
	}

	if method == "POST" {
		siteUrl := url
		pattern := network.RequestPattern{URLPattern: &siteUrl}
		patterns := []network.RequestPattern{pattern}

		interArgs := network.NewSetRequestInterceptionArgs(patterns)
		err = c.Network.SetRequestInterception(ctx, interArgs)
		if err != nil {
			return "", err
		}

		cl, err := c.Network.RequestIntercepted(ctx)
		if err != nil {
			return "", err
		}
		go func() {
			r, err := cl.Recv()
			if err != nil {
				//return err
				//panic(err)
			}

			interceptedArgs := network.NewContinueInterceptedRequestArgs(r.InterceptionID)
			interceptedArgs.Headers = []byte(`{"Content-Type":"application/x-www-form-urlencoded"}`)
			interceptedArgs.SetMethod("POST")
			interceptedArgs.SetPostData(data)
			if err = c.Network.ContinueInterceptedRequest(ctx, interceptedArgs); err != nil {
				//return err
				//panic(err)
			}
		}()
	}

	// Create the Navigate arguments with the optional Referrer field set.
	navArgs := page.NewNavigateArgs(url).
		SetReferrer(url)
	_, err = c.Page.Navigate(ctx, navArgs)
	if err != nil {
		return "", err
	}

	// Wait until we have a DOMContentEventFired event.
	if _, err = domContent.Recv(); err != nil {
		return "", err
	}

	//fmt.Printf("Page loaded with frame ID: %s\n", nav.FrameID)

	// Fetch the document root node. We can pass nil here
	// since this method only takes optional arguments.
	doc, err := c.DOM.GetDocument(ctx, nil)
	if err != nil {
		return "", err
	}

	// Get the outer HTML for the page.
	result, err := c.DOM.GetOuterHTML(ctx, &dom.GetOuterHTMLArgs{
		NodeID: &doc.Root.NodeID,
	})
	if err != nil {
		return "", err
	}

	return result.OuterHTML, nil
}
```

**Comment by mafredri** [comment]
Hi, when you're downloading a file there will probably not be a page load, so there will never be a `DOMContentEventFired` event. 

Your code worked fine for me, as-is in both headless and headfull mode of Chrome 76.0.3809.36.

I used a pretty long timeout and the file downloaded just fine.

What you should be listening for is `Page.DownloadWillBegin`. The order of events that I observed is (I used a simple GET request for a binary file):

- `Page.navigate`
- `Network.requestWillBeSent`
- `Network.responseReceived` (this is where chrome detects it's a binary)
- `Network.loadingFailed` (page load cancelled because it's not a page)
- `Page.downloadWillBegin`
- ...Timeout

Surprisingly I did not observe any even after the download was done `¯\_(ツ)_/¯`.

(PS. Sorry, I wrote this a few days ago but apparently forgot to press submit).

**Comment by LuciferoO** [comment]
Thanks for your reply,I will try to make some tests.

In your reply, 
`Network.loadingFailed` (page load cancelled because it's not a page)".
So, I have another question to find some help from you:).
Beause, I can't get response of the page,
so I can't  find filename in header
`Content-disposition: attachment; filename=2017-03-13_2017-03-19.xml` 
to check if the file I donwloaded was success.

**Comment by LuciferoO** [comment]
Here is my code 
`func run(timeout time.Duration, target string) error {

        ctx, cancel := context.WithTimeout(context.Background(), timeout)
        defer cancel()	
        
        devt := devtool.New("http://127.0.0.1:9222")
	// pt, err := devt.Get(ctx, devtool.Page)
	// if err != nil {
	// 	pt, err = devt.Create(ctx)
	// 	if err != nil {
	// 		return err
	// 	}
	// }

	targetPage, err := devt.Create(ctx)
	if err != nil {
		fmt.Println("devtool create error, ", err)
		return err
	}

	conn, err := rpcc.DialContext(ctx, targetPage.WebSocketDebuggerURL, rpcc.WithWriteBufferSize(4096*6))
	if err != nil {
		return err
	}
	defer conn.Close()

	c := cdp.NewClient(conn)

	behaviorArgs := page.NewSetDownloadBehaviorArgs("allow")
	behaviorArgs.SetDownloadPath("./download/")
	c.Page.SetDownloadBehavior(ctx, behaviorArgs)

	defer c.Page.Close(ctx)

	navArgs := page.NewNavigateArgs(target) //.SetReferrer("https://duckduckgo.com")
	_, err = c.Page.Navigate(ctx, navArgs)
	if err != nil {
		return err
	}
	c.Network.Enable(ctx, nil)

	responseReceivedClient, err := c.Network.ResponseReceived(ctx)
	if err != nil {
		return err
	}

	responseReceiveReply, err := responseReceivedClient.Recv()

	if err != nil {
		return err
	}

	fmt.Println("[Headers]", responseReceiveReply.Response.HeadersText)
	return nil
	/*loadingFinishClient, err := c.Network.LoadingFinished(ctx)

	responseReceivedClient, err := c.Network.ResponseReceived(ctx)

	go func() {
		for {
			select {
			case <-loadingFinishClient.Ready():
				loadingClient, err := loadingFinishClient.Recv()
				if err != nil {
					//fmt.Println("loading Client recv error", err)
				} else {
					fmt.Println(loadingClient)
				}
			case <-responseReceivedClient.Ready():
				responseReceiveClient, err := responseReceivedClient.Recv()
				if err != nil {
					//fmt.Println("response error ", err)
				} else {
					fmt.Println(responseReceiveClient)
				}
			}
		}
	}()

	time.Sleep(20 * time.Second)
	*/

	return nil
}
`

**Comment by mafredri** [comment]
First, I'd recommend enabling logging (see the [Logging example](https://godoc.org/github.com/mafredri/cdp#ex-package--Logging) in GoDoc), this will help you debug and see what is happening behind the scenes.

Then, your program should work just fine if we change the orders around a bit:

```go
// ...
c.Page.Enable(ctx)
c.Network.Enable(ctx, nil)

responseReceivedClient, err := c.Network.ResponseReceived(ctx)
if err != nil {
	return err
}

navArgs := page.NewNavigateArgs(target)
_, err = c.Page.Navigate(ctx, navArgs)
if err != nil {
	return err
}

responseReceiveReply, err := responseReceivedClient.Recv()
if err != nil {
	return err
}
// ...
```

First we enable the domains (I added Page, because it contains the DownloadWillBegin event), then we create the event client, and only once everything is set up and ready, we navigate. Otherwise we can miss events between navigating and creating the event client.

**Comment by LuciferoO** [comment]
Thanks for your help，I solved my problem:)。
