### ISSUE TITLE
How to make sure everything is loaded? (PDF)

### ISSUE THREAD

**Issue by gulien** [mafredri/cdp#99]
Hello @mafredri 

Thanks again for this library, it helped me a lot for printing HTML to PDF 👍 

My question is quite simple: how to make sure everything is loaded?
By everything, I do not mean:
- Javascript rendering (should be possible by injecting a script which waits for a custom event). 

But:
- Google fonts, remote CSS / JavaScript files

As you know, this question is actually hard to answer 😄 

What I'm currently doing:
- I enable all events (https://github.com/thecodingmachine/gotenberg/blob/6.0.0/internal/pkg/printer/chrome.go#L82)
- I "wait" them (https://github.com/thecodingmachine/gotenberg/blob/6.0.0/internal/pkg/printer/chrome.go#L129)

But it does not seem to work for Google fonts.
Here is a workaround which I've been using before: https://github.com/thecodingmachine/gotenberg/blob/4.0.0/internal/pkg/printer/html.go#L106

But I'm pretty sure I'm doing something wrong.

Thank your for your help 😀

**Comment by mafredri** [comment]
Hi @gulien,

the events you're currently listening to don't wait for external resources, so we need another way to track those.

One way would be to listen to lifecycle events, like discussed and shown here: https://github.com/mafredri/cdp/issues/98#issuecomment-505103096, you'd probably be interested in the `networkidle` event.

Another way I've been using is to track all network requests made by listening to `Network.RequestWillBeSent` for new requests and tracking the request ID, and `Network.ResponseReceived` / `Network.LoadingFailed` for tracking completed requests. Combined with a debounce of say 5 seconds it has worked pretty well. This also allows you to write custom logic like bail on a failed request, unless it was cancelled, etc.

Hope that helps 😄.

**Comment by gulien** [comment]
Sorry for the late reply 😅 

Here is the file I'm trying to convert to PDF:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    <style>
        body {
            font-family: "Source Sans Pro", sans-serif;
            font-size: 10pt;
            background: white !important;
            color: black; !important;
        }
    </style>
</head>
<body>
    <h1>Title</h1>
</body>
</html>
```

I've implemented the first solution (`networkidle`):

```golang
if err := targetClient.Page.SetLifecycleEventsEnabled(ctx, page.NewSetLifecycleEventsEnabledArgs(true)); err != nil {
  return err
}
# ...
lifecycleEvent, err := client.Page.LifecycleEvent(ctx)
if err != nil {
  return err
}
defer lifecycleEvent.Close()
# ...
if _, err := lifecycleEvent.Recv(); err != nil {
  return err
}
```

No success so far.

So first question: did I implement it correctly? 😄 

For `Network.RequestWillBeSent`, I'm not sure about what to do.
Let's say I create all the clients:

```golang
requestWillBeSent, err := client.Network.RequestWillBeSent(ctx)
if err != nil {
  return err
}
defer requestWillBeSent.Close()
responseReceived, err := client.Network.ResponseReceived(ctx)
if err != nil {
  return err
}
defer responseReceived.Close()
loadingFailed, err := client.Network.LoadingFailed(ctx)
if err != nil {
  return err
}
defer loadingFailed.Close()
```

Now I may use `Recv()` method of those clients which returns a reply with a `RequestID`. 
I fail to understand how can I track more than one request? 🤔 

Thank you!

**Comment by mafredri** [comment]
> So first question: did I implement it correctly? 😄

Hard to say from the code sample as it's only part of it. Did you also enable the page domain? (`Page.Enable()`). And there can be other types of lifecycle events so you need to wait for the right one. Maybe something more in this fashion:

```go
for {
	ev, err := lifecycleEvent.Recv()
	if err != nil {
		return err
	}
	fmt.Println(ev.Name)
	if ev.Name == "networkIdle" {
		break
	}
}
```

With regards to the second option I'd recommend spinning up a goroutine to monitor the network events and keep state. Even better if we synchronize all clients via `cdp.Sync` first so we receive all events in order.

Here's a boilerplate that should help get you started (actual request tracking implementation is left for the reader 😄).

```go
requestWillBeSent, err := c.Network.RequestWillBeSent(ctx)
if err != nil {
	return err
}
responseReceived, err := c.Network.ResponseReceived(ctx)
if err != nil {
	return err
}
loadingFailed, err := c.Network.LoadingFailed(ctx)
if err != nil {
	return err
}

err = cdp.Sync(
	requestWillBeSent,
	responseReceived,
	loadingFailed,
)
if err != nil {
	return err
}

go func() {
	defer requestWillBeSent.Close()
	defer responseReceived.Close()
	defer loadingFailed.Close()

	for {
		select {
		case <-requestWillBeSent.Ready():
			ev, err := requestWillBeSent.Recv()
			if err != nil { // Handle error...
				return
			}

			// Track the request ID.
			_ = ev

		case <-responseReceived.Ready():
			ev, err := responseReceived.Recv()
			if err != nil { // Handle error...
				return
			}

			// Check status codes?
			// Done with this request...
			_ = ev
			
		case <-loadingFailed.Ready():
			ev, err := loadingFailed.Recv()
			if err != nil { // Handle error...
				return
			}

			if ev.Canceled != nil && *ev.Canceled {
				// Canceled requests are probably OK.
			}
			
			// Abort?
		}
	}
}()
```

**Comment by mafredri** [comment]
Actually, I just realized the above implementation can very well be used without a goroutine as well, so dealers choice 😄.

**Comment by gulien** [comment]
Thank you very much @mafredri for this complete answer 👍 

> Hard to say from the code sample as it's only part of it. Did you also enable the page domain? (Page.Enable()).

Yes my bad, my code snippet was a simplification of what I've actually did.

> And there can be other types of lifecycle events so you need to wait for the right one.

Indeed, the `for` did the trick! It works like a charm now: the google fonts are correctly loaded 😄

The second option might be useful for other usage, thank you for the insights 👍
